# Generated by Django 5.1 on 2026-07-28 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer_service", "0004_conversation_handled_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="conversation",
            new_name="customer_se_user_id_e30ad1_idx",
            old_name="cs_conv_user_status_idx",
        ),
        migrations.RenameIndex(
            model_name="conversation",
            new_name="customer_se_status_39dd0b_idx",
            old_name="cs_conv_status_idx",
        ),
        migrations.RenameIndex(
            model_name="conversation",
            new_name="customer_se_admin_i_b30015_idx",
            old_name="cs_conv_admin_status_idx",
        ),
        migrations.RenameIndex(
            model_name="conversation",
            new_name="customer_se_group_i_b8516d_idx",
            old_name="cs_conv_group_status_idx",
        ),
        migrations.RenameIndex(
            model_name="message",
            new_name="customer_se_convers_93f5f5_idx",
            old_name="cs_msg_conv_created_idx",
        ),
        migrations.RenameIndex(
            model_name="message",
            new_name="customer_se_convers_4020e8_idx",
            old_name="cs_msg_conv_read_sender_idx",
        ),
        migrations.AlterField(
            model_name="conversation",
            name="handled_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="开始处理时间"),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="handled_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="handled_conversations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="当前处理人",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="card_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="商品卡片引用数据（仅存 spu_id + order_id，展示时从 SPU 实时查询）",
                verbose_name="卡片数据",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="msg_type",
            field=models.CharField(
                choices=[
                    ("text", "文字"),
                    ("image", "图片"),
                    ("video", "视频"),
                    ("product_link", "商品链接"),
                    ("cart_share", "购物车分享"),
                    ("product_card", "商品卡片"),
                    ("order_card", "订单卡片"),
                ],
                default="text",
                max_length=16,
                verbose_name="消息类型",
            ),
        ),
    ]
