# Generated by Django 5.2.15 on 2026-06-18 03:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
                ('spu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='goods.spu', verbose_name='商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '收藏',
                'verbose_name_plural': '收藏',
                'db_table': 'lovegoods_favorite',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='lovegoods_f_user_id_7dd5fe_idx'), models.Index(fields=['spu'], name='lovegoods_f_spu_id_6b7fe7_idx')],
                'unique_together': {('user', 'spu')},
            },
        ),
    ]
