# Generated by Django 5.1 on 2026-07-06 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("goods", "0014_sku_version"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BrowseHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "viewed_at",
                    models.DateTimeField(auto_now=True, verbose_name="最近浏览时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="首次浏览时间"),
                ),
                (
                    "spu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="browse_history",
                        to="goods.spu",
                        verbose_name="浏览商品",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="browse_history",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "浏览历史",
                "verbose_name_plural": "浏览历史",
                "db_table": "tracking_browse_history",
                "ordering": ["-viewed_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-viewed_at"], name="idx_browse_user_viewed"
                    ),
                    models.Index(fields=["spu"], name="idx_browse_spu"),
                ],
                "unique_together": {("user", "spu")},
            },
        ),
    ]
