# Generated by Django 5.2.15 on 2026-06-18 03:32

import apps.payment.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_no', models.CharField(default=apps.payment.models.generate_payment_no, max_length=32, unique=True, verbose_name='支付流水号')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='支付币种')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='支付金额')),
                ('method', models.CharField(choices=[('paypal', 'PayPal'), ('stripe', 'Stripe'), ('alipay', 'Alipay')], max_length=20, verbose_name='支付方式')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='支付状态')),
                ('gateway_payment_id', models.CharField(blank=True, default='', max_length=255, verbose_name='网关支付ID')),
                ('gateway_data', models.JSONField(default=dict, verbose_name='网关原始数据')),
                ('remark', models.CharField(blank=True, default='', max_length=200, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_logs', to='order.order', verbose_name='订单')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '支付记录',
                'verbose_name_plural': '支付记录',
                'db_table': 'payment_payment_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='payment_pay_user_id_635b9e_idx'), models.Index(fields=['order'], name='payment_pay_order_i_32f06d_idx'), models.Index(fields=['gateway_payment_id'], name='payment_pay_gateway_dd1d3a_idx')],
            },
        ),
    ]
