# Generated by Django 5.1 on 2026-07-28 09:16

import apps.payment.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0002_payment_event"),
    ]

    operations = [
        migrations.CreateModel(
            name="RefundLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "refund_no",
                    models.CharField(
                        default=apps.payment.models.generate_refund_no,
                        max_length=32,
                        unique=True,
                        verbose_name="退款流水号",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="退款金额"
                    ),
                ),
                (
                    "reason",
                    models.CharField(default="", max_length=500, verbose_name="退款原因"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="退款状态",
                    ),
                ),
                (
                    "gateway_refund_id",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="网关退款ID"
                    ),
                ),
                ("gateway_data", models.JSONField(default=dict, verbose_name="网关原始数据")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "退款记录",
                "verbose_name_plural": "退款记录",
                "db_table": "payment_refund_log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RenameIndex(
            model_name="paymentevent",
            new_name="payment_eve_gateway_191d4c_idx",
            old_name="payment_eve_gateway_47b762_idx",
        ),
        migrations.AlterField(
            model_name="paymentlog",
            name="method",
            field=models.CharField(
                choices=[
                    ("mock", "Mock (dev/staging only)"),
                    ("paypal", "PayPal"),
                    ("stripe", "Stripe"),
                    ("alipay", "Alipay"),
                ],
                max_length=20,
                verbose_name="支付方式",
            ),
        ),
        migrations.AddField(
            model_name="refundlog",
            name="payment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="refunds",
                to="payment.paymentlog",
                verbose_name="原支付记录",
            ),
        ),
        migrations.AddIndex(
            model_name="refundlog",
            index=models.Index(
                fields=["payment"], name="payment_ref_payment_80064f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="refundlog",
            index=models.Index(
                fields=["refund_no"], name="payment_ref_refund__01a3fb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="refundlog",
            index=models.Index(fields=["status"], name="payment_ref_status_8f98c1_idx"),
        ),
    ]
