# Generated by Django 5.2.17 on 2026-09-02 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_refundlog_reconcile_attempts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentlog',
            name='method',
            field=models.CharField(choices=[('paypal', 'PayPal'), ('stripe', 'Stripe')], max_length=20, verbose_name='支付方式'),
        ),
    ]
