# Generated by Django 5.2.17 on 2026-10-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_alter_paymentlog_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentlog',
            name='method',
            field=models.CharField(choices=[('paypal', 'PayPal'), ('stripe', 'Stripe'), ('creem', 'Creem')], max_length=20, verbose_name='支付方式'),
        ),
    ]