# Generated by Django 5.2.15 on 2026-06-18 03:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
        ('order', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='评分')),
                ('content', models.TextField(blank=True, default='', verbose_name='评价内容')),
                ('images', models.JSONField(default=list, verbose_name='晒图')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='匿名')),
                ('is_active', models.BooleanField(default=True, verbose_name='显示')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='评价时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='order.orderitem', verbose_name='订单项')),
                ('spu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='goods.spu', verbose_name='商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '商品评价',
                'verbose_name_plural': '商品评价',
                'db_table': 'review_review',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['spu', 'is_active'], name='review_revi_spu_id_73aa64_idx'), models.Index(fields=['user'], name='review_revi_user_id_1c40d7_idx')],
                'unique_together': {('user', 'order_item')},
            },
        ),
    ]
