# Generated by Django 5.2.17 on 2026-08-07 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrier',
            options={'ordering': ['name'], 'verbose_name': '物流承运商', 'verbose_name_plural': '物流承运商'},
        ),
        migrations.AlterModelOptions(
            name='shipment',
            options={'ordering': ['-created_at'], 'verbose_name': '物流发货', 'verbose_name_plural': '物流发货'},
        ),
        migrations.AlterModelOptions(
            name='shippingrate',
            options={'ordering': ['carrier', 'min_value'], 'verbose_name': '运费规则', 'verbose_name_plural': '运费规则'},
        ),
        migrations.RemoveIndex(
            model_name='shippingrate',
            name='idx_sr_carrier_min',
        ),
        migrations.RenameIndex(
            model_name='shipment',
            new_name='logistics_s_order_i_4704a4_idx',
            old_name='idx_ship_order',
        ),
        migrations.RenameIndex(
            model_name='shipment',
            new_name='logistics_s_trackin_fbcdeb_idx',
            old_name='idx_ship_tracking',
        ),
        migrations.RenameIndex(
            model_name='shipment',
            new_name='logistics_s_status_2d3ba5_idx',
            old_name='idx_ship_status',
        ),
        migrations.AlterField(
            model_name='carrier',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='carrier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.carrier', verbose_name='承运商'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='shippingrate',
            name='carrier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='logistics.carrier'),
        ),
        migrations.AlterField(
            model_name='shippingrate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
