# Generated by Django 5.1 on 2026-06-19 05:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('goods', '0003_add_cart_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['user'], name='idx_cart_user'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['cart'], name='idx_cartitem_cart'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['sku'], name='idx_cartitem_sku'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['selected'], name='idx_cartitem_selected'),
        ),
    ]
