# Generated by Django 5.1 on 2026-06-19 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_add_cart_indexes'),
        ('goods', '0006_attribute_specname_sku_sales_sku_sku_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cart_items', to='goods.sku', verbose_name='SKU'),
        ),
    ]
