# Generated by Django 5.2.15 on 2026-06-18 03:32

import apps.users.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpiringToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '过期Token',
                'verbose_name_plural': '过期Token',
                'db_table': 'users_expiringtoken',
            },
        ),
        migrations.CreateModel(
            name='SMSVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('country_code', models.CharField(max_length=10)),
                ('code', models.CharField(max_length=6)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': '短信验证码',
                'verbose_name_plural': '短信验证码',
                'db_table': 'users_sms_verification_code',
                'indexes': [models.Index(fields=['phone', 'country_code', '-created_at'], name='users_sms_v_phone_34d1c6_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(blank=True, default='', help_text='国际区号，如 +86（选填）', max_length=10, validators=[apps.users.models.validate_country_code])),
                ('phone', models.CharField(blank=True, default='', help_text='手机号（不含区号）', max_length=20, validators=[apps.users.models.validate_phone])),
                ('phone_verified', models.BooleanField(default=False, help_text='手机号是否已通过短信验证')),
                ('username_changed_at', models.DateTimeField(blank=True, help_text='上次修改用户名的时间（用于冷却期判断）', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户扩展信息',
                'verbose_name_plural': '用户扩展信息',
                'db_table': 'users_userprofile',
                'constraints': [models.UniqueConstraint(condition=models.Q(('phone', ''), _negated=True), fields=('country_code', 'phone'), name='unique_phone_per_country_code')],
            },
        ),
    ]
