# Generated by Django 5.1 on 2026-07-28 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("google", "Google"), ("facebook", "Facebook")],
                        max_length=20,
                        verbose_name="提供商",
                    ),
                ),
                (
                    "provider_id",
                    models.CharField(max_length=255, verbose_name="提供商用户ID"),
                ),
                (
                    "extra_data",
                    models.JSONField(blank=True, default=dict, verbose_name="额外数据"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="绑定时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_accounts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "社交账号",
                "verbose_name_plural": "社交账号",
                "db_table": "users_social_account",
                "indexes": [
                    models.Index(
                        fields=["provider", "provider_id"],
                        name="users_socia_provide_25a896_idx",
                    ),
                    models.Index(
                        fields=["user"], name="users_socia_user_id_5f8018_idx"
                    ),
                ],
                "unique_together": {("provider", "provider_id")},
            },
        ),
    ]
