# Generated by Django 5.2.17 on 2026-09-02 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='template_type',
            field=models.CharField(choices=[('verify_code', '邮箱验证码'), ('order_notice', '订单通知'), ('reset_password', '密码重置'), ('admin_welcome', '管理员欢迎邮件')], max_length=32, unique=True, verbose_name='模板类型'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, default='', help_text='部门（可选）', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='邮箱是否已验证（仅欢迎邮件验证链接可置 true）'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='locale',
            field=models.CharField(blank=True, default='zh-CN', help_text='语言偏好（如 zh-CN / en-US）', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='must_reset_password',
            field=models.BooleanField(default=True, help_text='首次登录是否强制修改密码（本期仅存储）'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='note',
            field=models.TextField(blank=True, default='', help_text='备注（可选）'),
        ),
    ]
