# Generated by Django 5.1 on 2026-07-09 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Term",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="标题")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("terms", "用户协议"),
                            ("privacy", "隐私政策"),
                            ("refund", "退款政策"),
                            ("shipping", "配送说明"),
                            ("cookies", "Cookie 政策"),
                            ("other", "其他"),
                        ],
                        db_index=True,
                        default="terms",
                        max_length=20,
                        verbose_name="类型",
                    ),
                ),
                ("content", models.TextField(verbose_name="内容")),
                (
                    "version",
                    models.CharField(
                        help_text="如 1.0, 2.1", max_length=20, verbose_name="版本号"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="只显示最新的一条生效条款", verbose_name="是否生效"
                    ),
                ),
                ("effective_date", models.DateTimeField(verbose_name="生效日期")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "用户条款",
                "verbose_name_plural": "用户条款",
                "db_table": "terms_term",
                "ordering": ["-effective_date"],
                "indexes": [
                    models.Index(
                        fields=["type", "is_active"], name="terms_term_type_d82fce_idx"
                    )
                ],
            },
        ),
    ]
