# Generated by Django 5.2.15 on 2026-06-18 03:32

import apps.promotion.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=apps.promotion.models.generate_coupon_code, max_length=50, unique=True, verbose_name='券码')),
                ('discount_type', models.CharField(choices=[('fixed', 'Fixed Amount'), ('percent', 'Percentage Off')], default='fixed', max_length=20, verbose_name='优惠类型')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='优惠值')),
                ('min_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='最低消费门槛')),
                ('max_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='最高折扣上限（百分比券用）')),
                ('stackable', models.BooleanField(default=False, verbose_name='可叠加')),
                ('total_count', models.PositiveIntegerField(default=0, verbose_name='发行总量')),
                ('claimed_count', models.PositiveIntegerField(default=0, verbose_name='已领取数量')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='已使用数量')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_coupons', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '优惠券',
                'verbose_name_plural': '优惠券',
                'db_table': 'promotion_coupon',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CouponScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_type', models.CharField(choices=[('spu', 'SPU'), ('category', 'Category'), ('brand', 'Brand')], max_length=20, verbose_name='范围类型')),
                ('target_id', models.PositiveIntegerField(verbose_name='目标 ID')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='promotion.coupon', verbose_name='优惠券')),
            ],
            options={
                'verbose_name': '优惠券适用范围',
                'verbose_name_plural': '优惠券适用范围',
                'db_table': 'promotion_coupon_scope',
            },
        ),
        migrations.CreateModel(
            name='DiscountActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='活动名称')),
                ('type', models.CharField(choices=[('full_reduction', 'Full Reduction'), ('percent_off', 'Percent Off'), ('each_full', 'Each Full')], max_length=30, verbose_name='活动类型')),
                ('rule', models.JSONField(default=list, verbose_name='活动规则')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_activities', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '折扣活动',
                'verbose_name_plural': '折扣活动',
                'db_table': 'promotion_activity',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivitySKURelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='活动价')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_relations', to='goods.sku', verbose_name='SKU')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sku_relations', to='promotion.discountactivity', verbose_name='活动')),
            ],
            options={
                'verbose_name': '活动 SKU 关联',
                'verbose_name_plural': '活动 SKU 关联',
                'db_table': 'promotion_activity_sku',
            },
        ),
        migrations.CreateModel(
            name='UserCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('unused', 'Unused'), ('used', 'Used'), ('expired', 'Expired')], default='unused', max_length=20, verbose_name='状态')),
                ('claimed_at', models.DateTimeField(auto_now_add=True, verbose_name='领取时间')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='使用时间')),
                ('used_order_no', models.CharField(blank=True, default='', max_length=20, verbose_name='使用订单号')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_coupons', to='promotion.coupon', verbose_name='优惠券')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_coupons', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户优惠券',
                'verbose_name_plural': '用户优惠券',
                'db_table': 'promotion_user_coupon',
                'ordering': ['-claimed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['code'], name='promotion_c_code_3b6474_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['is_active', 'start_time', 'end_time'], name='promotion_c_is_acti_2af943_idx'),
        ),
        migrations.AddIndex(
            model_name='couponscope',
            index=models.Index(fields=['coupon'], name='promotion_c_coupon__e2dd04_idx'),
        ),
        migrations.AddIndex(
            model_name='couponscope',
            index=models.Index(fields=['scope_type', 'target_id'], name='promotion_c_scope_t_af4759_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='couponscope',
            unique_together={('coupon', 'scope_type', 'target_id')},
        ),
        migrations.AddIndex(
            model_name='discountactivity',
            index=models.Index(fields=['start_time', 'end_time'], name='promotion_a_start_t_991e30_idx'),
        ),
        migrations.AddIndex(
            model_name='activityskurelation',
            index=models.Index(fields=['activity'], name='promotion_a_activit_6f95fc_idx'),
        ),
        migrations.AddIndex(
            model_name='activityskurelation',
            index=models.Index(fields=['sku'], name='promotion_a_sku_id_200800_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='activityskurelation',
            unique_together={('activity', 'sku')},
        ),
        migrations.AlterUniqueTogether(
            name='usercoupon',
            unique_together={('user', 'coupon')},
        ),
    ]
