# Generated by Django 5.1 on 2026-06-19 05:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='usercoupon',
            index=models.Index(fields=['user', 'status'], name='idx_uc_user_status'),
        ),
        migrations.AddIndex(
            model_name='usercoupon',
            index=models.Index(fields=['coupon'], name='idx_uc_coupon'),
        ),
        migrations.AddIndex(
            model_name='usercoupon',
            index=models.Index(fields=['used_order_no'], name='idx_uc_order_no'),
        ),
    ]
