# Generated by Django 5.1 on 2026-06-19 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0004_add_coupon_scope_and_activity_sku_timestamps'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='name',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='优惠券名称'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='per_user_limit',
            field=models.PositiveIntegerField(default=1, verbose_name='每人限领数量'),
        ),
    ]
