# Generated by Django 5.2.16 on 2026-07-28 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0017_adminnotification_expires_at_and_more"),
        ("promotion", "0006_coupon_lifecycle"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="target_audience",
            field=models.CharField(blank=True, default="all", max_length=200),
        ),
        migrations.CreateModel(
            name="CouponApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("coupon_name", models.CharField(default="", max_length=100)),
                (
                    "coupon_code",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("fixed", "Fixed Amount"),
                            ("percent", "Percentage Off"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "min_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "max_discount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("stackable", models.BooleanField(default=False)),
                ("total_count", models.PositiveIntegerField(default=1000)),
                ("per_user_limit", models.PositiveIntegerField(default=1)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("applicable_categories", models.JSONField(blank=True, default=list)),
                ("applicable_products", models.JSONField(blank=True, default=list)),
                ("applicable_brands", models.JSONField(blank=True, default=list)),
                ("applicable_category_names", models.TextField(blank=True, default="")),
                ("applicable_product_names", models.TextField(blank=True, default="")),
                ("applicable_brand_names", models.TextField(blank=True, default="")),
                (
                    "expected_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("expected_usage_count", models.PositiveIntegerField(default=0)),
                (
                    "target_audience",
                    models.CharField(blank=True, default="all", max_length=200),
                ),
                ("campaign_purpose", models.TextField(blank=True, default="")),
                ("reason", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("scheduled", "Scheduled"),
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("expired", "Expired"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("review_comment", models.TextField(blank=True, default="")),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "admin_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="coupon_applications",
                        to="goods.admingroup",
                    ),
                ),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="coupon_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "coupon",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="application",
                        to="promotion.coupon",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_coupon_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "promotion_coupon_application",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CouponApprovalHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_status",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("to_status", models.CharField(max_length=20)),
                ("comment", models.TextField(blank=True, default="")),
                ("snapshot", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_history",
                        to="promotion.couponapplication",
                    ),
                ),
            ],
            options={
                "db_table": "promotion_coupon_approval_history",
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="couponapplication",
            index=models.Index(
                fields=["status", "-created_at"], name="idx_ca_status_created"
            ),
        ),
        migrations.AddIndex(
            model_name="couponapplication",
            index=models.Index(
                fields=["applicant", "-created_at"], name="idx_ca_app_created"
            ),
        ),
        migrations.AddIndex(
            model_name="couponapplication",
            index=models.Index(
                fields=["admin_group", "status"], name="idx_ca_group_status"
            ),
        ),
    ]
