# Generated by Django 5.2.17 on 2026-08-11 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0009_coupon_target_audience_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='用户凭此码领取对应基础券', max_length=32, unique=True, verbose_name='推广码')),
                ('name', models.CharField(blank=True, default='', max_length=128, verbose_name='渠道/推广人')),
                ('note', models.TextField(blank=True, default='', verbose_name='备注')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('claim_count', models.PositiveIntegerField(default=0, verbose_name='领取数')),
                ('paid_order_count', models.PositiveIntegerField(default=0, verbose_name='付款订单数')),
                ('gmv', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='引流 GMV')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_codes', to='promotion.coupon', verbose_name='基础券')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_promo_codes', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '专属推广码',
                'verbose_name_plural': '专属推广码',
                'db_table': 'promotion_promocode',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='usercoupon',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_coupons', to='promotion.promocode', verbose_name='推广码'),
        ),
        migrations.AddIndex(
            model_name='usercoupon',
            index=models.Index(fields=['promo_code'], name='idx_uc_promo_code'),
        ),
        migrations.AddIndex(
            model_name='promocode',
            index=models.Index(fields=['coupon'], name='promotion_p_coupon__c3c41b_idx'),
        ),
        migrations.AddIndex(
            model_name='promocode',
            index=models.Index(fields=['code'], name='promotion_p_code_f12719_idx'),
        ),
    ]
