# Generated by Django 5.2.17 on 2026-09-02 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0011_alter_activityskurelation_activity_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountactivity',
            name='type',
            field=models.CharField(choices=[('full_reduction', 'Full Reduction'), ('percent_off', 'Percent Off'), ('each_full', 'Each Full'), ('flat_off', 'Flat Off')], max_length=30, verbose_name='活动类型'),
        ),
    ]
