# Generated by Django 5.2.15 on 2026-06-18 03:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='品牌名称')),
                ('logo_url', models.CharField(blank=True, default='', max_length=500, verbose_name='Logo 图片 URL')),
                ('description', models.TextField(blank=True, default='', verbose_name='品牌描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '品牌',
                'verbose_name_plural': '品牌',
                'db_table': 'goods_brand',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec_values', models.JSONField(default=dict, verbose_name='规格值（JSON）')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='售价（元）')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='折扣价（元）')),
                ('stock', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='库存数量')),
                ('image_url', models.CharField(blank=True, default='', max_length=500, verbose_name='SKU 图片 URL')),
                ('shelf_status', models.CharField(choices=[('on', 'On'), ('off', 'Off')], default='on', max_length=10, verbose_name='上下架状态')),
                ('alert_threshold', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='库存预警阈值')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '商品 SKU',
                'verbose_name_plural': '商品 SKU',
                'db_table': 'goods_sku',
                'ordering': ['spu', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='标签名称')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '商品标签',
                'verbose_name_plural': '商品标签',
                'db_table': 'goods_tag',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AdminGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='组名称')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='标识符')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_admin_groups', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '管理组',
                'verbose_name_plural': '管理组',
                'db_table': 'goods_admin_group',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='分类名称')),
                ('level', models.PositiveSmallIntegerField(default=1, verbose_name='层级')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('admin_group', models.ForeignKey(blank=True, help_text='二级分类绑定管理组，组内成员可管理该分类及其下级', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_categories', to='goods.admingroup', verbose_name='归属管理组')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_categories', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='goods.category', verbose_name='上级分类')),
            ],
            options={
                'verbose_name': '商品分类',
                'verbose_name_plural': '商品分类',
                'db_table': 'goods_category',
                'ordering': ['level', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CategoryRenameApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_name', models.CharField(max_length=100, verbose_name='新名称')),
                ('reason', models.TextField(blank=True, default='', verbose_name='申请理由')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='状态')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_rename_applications', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rename_applications', to='goods.category', verbose_name='目标分类')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_category_rename_applications', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
            ],
            options={
                'verbose_name': '分类改名申请',
                'verbose_name_plural': '分类改名申请',
                'db_table': 'goods_category_rename_app',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CouponApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_type', models.CharField(choices=[('fixed', 'Fixed Amount'), ('percent', 'Percentage Off')], max_length=20, verbose_name='优惠类型')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='优惠值')),
                ('min_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='最低消费门槛')),
                ('max_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='最高折扣上限')),
                ('stackable', models.BooleanField(default=False, verbose_name='可叠加')),
                ('total_count', models.PositiveIntegerField(default=1000, verbose_name='发行总量')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='生效时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='截止时间')),
                ('reason', models.TextField(blank=True, default='', verbose_name='申请理由')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='状态')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_applications', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_coupon_applications', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
            ],
            options={
                'verbose_name': '优惠券申请',
                'verbose_name_plural': '优惠券申请',
                'db_table': 'goods_coupon_app',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoodsAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50, verbose_name='操作类型')),
                ('resource_type', models.CharField(max_length=50, verbose_name='资源类型')),
                ('resource_id', models.PositiveIntegerField(verbose_name='资源 ID')),
                ('changes', models.JSONField(default=dict, verbose_name='变更内容')),
                ('extra_data', models.JSONField(default=dict, verbose_name='附加数据')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '审计日志',
                'verbose_name_plural': '审计日志',
                'db_table': 'goods_audit_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaderChangeApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, default='', verbose_name='申请理由')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='状态')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_leader_change_applications', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leader_change_applications', to='goods.admingroup', verbose_name='目标管理组')),
                ('new_leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leader_change_applications', to=settings.AUTH_USER_MODEL, verbose_name='新组长')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_leader_change_applications', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
            ],
            options={
                'verbose_name': '组长变更申请',
                'verbose_name_plural': '组长变更申请',
                'db_table': 'goods_leader_change_app',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='旧价格')),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='新价格')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='变更时间')),
                ('reason', models.CharField(blank=True, default='', max_length=200, verbose_name='变更原因')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_changes', to=settings.AUTH_USER_MODEL, verbose_name='变更人')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_histories', to='goods.sku', verbose_name='SKU')),
            ],
            options={
                'verbose_name': '价格历史',
                'verbose_name_plural': '价格历史',
                'db_table': 'goods_price_history',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='SPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, validators=[django.core.validators.MaxLengthValidator(200)], verbose_name='商品名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='商品描述')),
                ('main_image', models.CharField(blank=True, default='', max_length=500, verbose_name='主图 URL')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('on_sale', 'On Sale'), ('off_sale', 'Off Sale')], default='draft', max_length=20, verbose_name='状态')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('review_comment', models.CharField(blank=True, default='', max_length=500, verbose_name='审批意见')),
                ('scheduled_publish_at', models.DateTimeField(blank=True, null=True, verbose_name='定时上架时间')),
                ('scheduled_unpublish_at', models.DateTimeField(blank=True, null=True, verbose_name='定时下架时间')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spus', to='goods.brand', verbose_name='品牌')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spus', to='goods.category', verbose_name='分类')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_spus', to=settings.AUTH_USER_MODEL, verbose_name='删除人')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_spus', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_spus', to=settings.AUTH_USER_MODEL, verbose_name='提交人')),
            ],
            options={
                'verbose_name': '商品 SPU',
                'verbose_name_plural': '商品 SPU',
                'db_table': 'goods_spu',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='sku',
            name='spu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skus', to='goods.spu', verbose_name='SPU'),
        ),
        migrations.CreateModel(
            name='ProductOperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50, verbose_name='操作类型')),
                ('field_name', models.CharField(blank=True, default='', max_length=100, verbose_name='字段名')),
                ('old_value', models.TextField(blank=True, default='', verbose_name='旧值')),
                ('new_value', models.TextField(blank=True, default='', verbose_name='新值')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_operations', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('spu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_logs', to='goods.spu', verbose_name='SPU')),
            ],
            options={
                'verbose_name': '商品操作日志',
                'verbose_name_plural': '商品操作日志',
                'db_table': 'goods_operation_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SPUTagRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('spu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_relations', to='goods.spu', verbose_name='SPU')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spu_relations', to='goods.tag', verbose_name='标签')),
            ],
            options={
                'verbose_name': 'SPU 标签关联',
                'verbose_name_plural': 'SPU 标签关联',
                'db_table': 'goods_spu_tag_relation',
            },
        ),
        migrations.CreateModel(
            name='AdminGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('leader', 'Leader'), ('member', 'Member')], default='member', max_length=20, verbose_name='角色')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Active'), (2, 'Away'), (3, 'Leave')], default=1, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='goods.admingroup', verbose_name='所属管理组')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_group_memberships', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '管理组成员',
                'verbose_name_plural': '管理组成员',
                'db_table': 'goods_admin_group_member',
                'ordering': ['group', 'id'],
                'indexes': [models.Index(fields=['user', 'status'], name='goods_admin_user_id_a9d804_idx'), models.Index(fields=['group', 'role'], name='goods_admin_group_i_20e92e_idx')],
                'unique_together': {('group', 'user')},
            },
        ),
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('application_submitted', 'Application Submitted'), ('application_approved', 'Application Approved'), ('application_rejected', 'Application Rejected'), ('spu_submitted', 'SPU Submitted'), ('spu_approved', 'SPU Approved'), ('spu_rejected', 'SPU Rejected'), ('leader_changed', 'Leader Changed'), ('batch_completed', 'Batch Completed'), ('scheduled_published', 'Scheduled Published'), ('stock_alert', 'Stock Alert')], max_length=30, verbose_name='通知类型')),
                ('title', models.CharField(max_length=200, verbose_name='通知标题')),
                ('content', models.TextField(blank=True, default='', verbose_name='通知内容')),
                ('related_type', models.CharField(blank=True, default='', max_length=50, verbose_name='关联资源类型')),
                ('related_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='关联资源 ID')),
                ('is_read', models.BooleanField(default=False, verbose_name='已读')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='阅读时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_notifications', to=settings.AUTH_USER_MODEL, verbose_name='接收人')),
            ],
            options={
                'verbose_name': '管理后台通知',
                'verbose_name_plural': '管理后台通知',
                'db_table': 'goods_admin_notification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='goods_admin_user_id_704fb8_idx'), models.Index(fields=['user', '-created_at'], name='goods_admin_user_id_670396_idx'), models.Index(fields=['type'], name='goods_admin_type_9474ed_idx')],
            },
        ),
        migrations.CreateModel(
            name='BrandRenameApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_name', models.CharField(max_length=100, verbose_name='新名称')),
                ('reason', models.TextField(blank=True, default='', verbose_name='申请理由')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='状态')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_rename_applications', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rename_applications', to='goods.brand', verbose_name='目标品牌')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_brand_rename_applications', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
            ],
            options={
                'verbose_name': '品牌改名申请',
                'verbose_name_plural': '品牌改名申请',
                'db_table': 'goods_brand_rename_app',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='goods_brand_status_975011_idx'), models.Index(fields=['applicant', '-created_at'], name='goods_brand_applica_997eef_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent', 'is_active'], name='goods_categ_parent__7c4d1b_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['level', 'is_active'], name='goods_categ_level_b3b88e_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['admin_group'], name='goods_categ_admin_g_dfd99b_idx'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.CheckConstraint(condition=models.Q(('level__gte', 1), ('level__lte', 3)), name='category_level_range'),
        ),
        migrations.AddIndex(
            model_name='categoryrenameapplication',
            index=models.Index(fields=['status'], name='goods_categ_status_587399_idx'),
        ),
        migrations.AddIndex(
            model_name='categoryrenameapplication',
            index=models.Index(fields=['applicant', '-created_at'], name='goods_categ_applica_4b944f_idx'),
        ),
        migrations.AddIndex(
            model_name='couponapplication',
            index=models.Index(fields=['status'], name='goods_coupo_status_d494b9_idx'),
        ),
        migrations.AddIndex(
            model_name='couponapplication',
            index=models.Index(fields=['applicant', '-created_at'], name='goods_coupo_applica_091d38_idx'),
        ),
        migrations.AddIndex(
            model_name='goodsauditlog',
            index=models.Index(fields=['resource_type', 'resource_id'], name='goods_audit_resourc_003db6_idx'),
        ),
        migrations.AddIndex(
            model_name='goodsauditlog',
            index=models.Index(fields=['user', '-created_at'], name='goods_audit_user_id_977a25_idx'),
        ),
        migrations.AddIndex(
            model_name='goodsauditlog',
            index=models.Index(fields=['action'], name='goods_audit_action_babe5d_idx'),
        ),
        migrations.AddIndex(
            model_name='leaderchangeapplication',
            index=models.Index(fields=['status'], name='goods_leade_status_f8e402_idx'),
        ),
        migrations.AddIndex(
            model_name='leaderchangeapplication',
            index=models.Index(fields=['applicant', '-created_at'], name='goods_leade_applica_dfee80_idx'),
        ),
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['sku', '-changed_at'], name='goods_price_sku_id_0da398_idx'),
        ),
        migrations.AddIndex(
            model_name='spu',
            index=models.Index(fields=['brand', 'status'], name='goods_spu_brand_i_9cccc8_idx'),
        ),
        migrations.AddIndex(
            model_name='spu',
            index=models.Index(fields=['category', 'status'], name='goods_spu_categor_f49ce2_idx'),
        ),
        migrations.AddIndex(
            model_name='spu',
            index=models.Index(fields=['status'], name='goods_spu_status_011041_idx'),
        ),
        migrations.AddIndex(
            model_name='spu',
            index=models.Index(fields=['deleted_at'], name='goods_spu_deleted_b5e63d_idx'),
        ),
        migrations.AddIndex(
            model_name='sku',
            index=models.Index(fields=['spu', 'shelf_status'], name='goods_sku_spu_id_4e490b_idx'),
        ),
        migrations.AddIndex(
            model_name='sku',
            index=models.Index(fields=['spu', 'stock'], name='goods_sku_spu_id_f0cf24_idx'),
        ),
        migrations.AddIndex(
            model_name='productoperationlog',
            index=models.Index(fields=['spu', '-created_at'], name='goods_opera_spu_id_808512_idx'),
        ),
        migrations.AddIndex(
            model_name='productoperationlog',
            index=models.Index(fields=['user', '-created_at'], name='goods_opera_user_id_8ae9af_idx'),
        ),
        migrations.AddIndex(
            model_name='productoperationlog',
            index=models.Index(fields=['action'], name='goods_opera_action_de7ca3_idx'),
        ),
        migrations.AddIndex(
            model_name='sputagrelation',
            index=models.Index(fields=['spu'], name='goods_spu_t_spu_id_820f71_idx'),
        ),
        migrations.AddIndex(
            model_name='sputagrelation',
            index=models.Index(fields=['tag'], name='goods_spu_t_tag_id_79897e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sputagrelation',
            unique_together={('spu', 'tag')},
        ),
    ]
