# Generated by Django 5.1 on 2026-06-19 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spu',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('on_sale', 'On Sale'), ('suspended', 'Suspended'), ('off_sale', 'Off Sale')], default='draft', max_length=20, verbose_name='状态'),
        ),
    ]
