# Generated by Django 5.1 on 2026-06-19 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_add_cart_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
