# Generated by Django 5.1 on 2026-06-19 09:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_add_tag_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='属性名称')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '属性',
                'verbose_name_plural': '属性',
                'db_table': 'goods_attribute',
            },
        ),
        migrations.CreateModel(
            name='SpecName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='规格名称')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '规格名称',
                'verbose_name_plural': '规格名称',
                'db_table': 'goods_spec_name',
            },
        ),
        migrations.AddField(
            model_name='sku',
            name='sales',
            field=models.PositiveIntegerField(default=0, verbose_name='销量'),
        ),
        migrations.AddField(
            model_name='sku',
            name='sku_code',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='SKU编码'),
        ),
        migrations.AlterField(
            model_name='brandrenameapplication',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rename_applications', to='goods.brand', verbose_name='目标品牌'),
        ),
        migrations.AlterField(
            model_name='categoryrenameapplication',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rename_applications', to='goods.category', verbose_name='目标分类'),
        ),
        migrations.AlterField(
            model_name='leaderchangeapplication',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leader_change_applications', to='goods.admingroup', verbose_name='目标管理组'),
        ),
        migrations.AlterField(
            model_name='leaderchangeapplication',
            name='new_leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leader_change_applications', to=settings.AUTH_USER_MODEL, verbose_name='新组长'),
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=256, verbose_name='属性值')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='goods.attribute', verbose_name='属性')),
            ],
            options={
                'verbose_name': '属性值',
                'verbose_name_plural': '属性值',
                'db_table': 'goods_attribute_value',
                'unique_together': {('attribute', 'value')},
            },
        ),
        migrations.CreateModel(
            name='SpecValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=128, verbose_name='规格值')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('spec_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='goods.specname', verbose_name='规格名称')),
            ],
            options={
                'verbose_name': '规格值',
                'verbose_name_plural': '规格值',
                'db_table': 'goods_spec_value',
                'unique_together': {('spec_name', 'value')},
            },
        ),
        migrations.CreateModel(
            name='SPUSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.specname', verbose_name='规格名称')),
                ('spu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spu_specs', to='goods.spu', verbose_name='SPU')),
            ],
            options={
                'verbose_name': 'SPU 规格',
                'verbose_name_plural': 'SPU 规格',
                'db_table': 'goods_spu_spec',
                'unique_together': {('spu', 'spec_name')},
            },
        ),
        migrations.CreateModel(
            name='SKUSpecValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sku_spec_values', to='goods.sku', verbose_name='SKU')),
                ('spec_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.specname', verbose_name='规格名称')),
                ('spec_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.specvalue', verbose_name='规格值')),
            ],
            options={
                'verbose_name': 'SKU 规格值',
                'verbose_name_plural': 'SKU 规格值',
                'db_table': 'goods_sku_spec_value',
                'unique_together': {('sku', 'spec_value')},
            },
        ),
        migrations.CreateModel(
            name='SPUAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.attribute', verbose_name='属性')),
                ('attribute_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.attributevalue', verbose_name='属性值')),
                ('spu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spu_attributes', to='goods.spu', verbose_name='SPU')),
            ],
            options={
                'verbose_name': 'SPU 属性',
                'verbose_name_plural': 'SPU 属性',
                'db_table': 'goods_spu_attribute',
                'unique_together': {('spu', 'attribute')},
            },
        ),
        migrations.CreateModel(
            name='SPUSpecValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.specvalue', verbose_name='规格值')),
                ('spu_spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spec_values', to='goods.spuspec', verbose_name='SPU规格')),
            ],
            options={
                'verbose_name': 'SPU 规格值',
                'verbose_name_plural': 'SPU 规格值',
                'db_table': 'goods_spu_spec_value',
                'unique_together': {('spu_spec', 'spec_value')},
            },
        ),
    ]
