# Generated by Django 5.1 on 2026-06-21 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_attribute_specname_sku_sales_sku_sku_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admingroup',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='描述'),
        ),
    ]
