# Generated by Django 5.1 on 2026-06-21 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_add_admin_group_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponapplication',
            name='coupon_code',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='优惠券码'),
        ),
    ]
