# Generated by Django 5.1 on 2026-06-21 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0009_add_category_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10, verbose_name='媒体类型')),
                ('thumb_url', models.CharField(blank=True, default='', max_length=500, verbose_name='缩略图 URL (200x200)')),
                ('list_url', models.CharField(blank=True, default='', max_length=500, verbose_name='列表图 URL (400x400)')),
                ('large_url', models.CharField(blank=True, default='', max_length=500, verbose_name='大图 URL (800x800)')),
                ('original_url', models.CharField(blank=True, default='', max_length=500, verbose_name='原图 URL (≤2048)')),
                ('video_url', models.CharField(blank=True, default='', max_length=500, verbose_name='视频 URL')),
                ('video_thumb_url', models.CharField(blank=True, default='', max_length=500, verbose_name='视频头帧缩略图 (200x200)')),
                ('video_list_url', models.CharField(blank=True, default='', max_length=500, verbose_name='视频头帧列表图 (400x400)')),
                ('video_large_url', models.CharField(blank=True, default='', max_length=500, verbose_name='视频头帧大图 (800x800)')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='状态')),
                ('redis_key', models.CharField(blank=True, default='', max_length=64, verbose_name='Redis 暂存 Key')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='文件大小 (bytes)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_media', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('spu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='goods.spu', verbose_name='所属 SPU')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_media', to=settings.AUTH_USER_MODEL, verbose_name='提交人')),
            ],
            options={
                'verbose_name': '商品媒体',
                'verbose_name_plural': '商品媒体',
                'db_table': 'goods_product_media',
                'ordering': ['spu', 'sort_order', 'id'],
                'indexes': [models.Index(fields=['spu', 'media_type', 'status'], name='goods_produ_spu_id_f0cb4c_idx'), models.Index(fields=['spu', 'sort_order'], name='goods_produ_spu_id_3ff681_idx'), models.Index(fields=['status'], name='goods_produ_status_04d845_idx')],
            },
        ),
    ]
