# Generated by Django 5.1 on 2026-06-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0010_productmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandrenameapplication',
            name='alternative_names',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='备选名称（多个用逗号分隔）'),
        ),
        migrations.AddField(
            model_name='brandrenameapplication',
            name='impact_spu_count',
            field=models.PositiveIntegerField(default=0, verbose_name='影响SPU数量'),
        ),
        migrations.AddField(
            model_name='brandrenameapplication',
            name='review_comment',
            field=models.TextField(blank=True, default='', verbose_name='审批意见'),
        ),
        migrations.AddField(
            model_name='categoryrenameapplication',
            name='alternative_names',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='备选名称（多个用逗号分隔）'),
        ),
        migrations.AddField(
            model_name='categoryrenameapplication',
            name='impact_spu_count',
            field=models.PositiveIntegerField(default=0, verbose_name='影响SPU数量'),
        ),
        migrations.AddField(
            model_name='categoryrenameapplication',
            name='review_comment',
            field=models.TextField(blank=True, default='', verbose_name='审批意见'),
        ),
        migrations.AddField(
            model_name='couponapplication',
            name='applicable_categories',
            field=models.TextField(blank=True, default='', verbose_name='适用分类（JSON格式）'),
        ),
        migrations.AddField(
            model_name='couponapplication',
            name='applicable_products',
            field=models.TextField(blank=True, default='', verbose_name='适用商品（JSON格式）'),
        ),
        migrations.AddField(
            model_name='couponapplication',
            name='coupon_name',
            field=models.CharField(default='', max_length=100, verbose_name='优惠券名称'),
        ),
        migrations.AddField(
            model_name='couponapplication',
            name='expected_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='预估成本'),
        ),
        migrations.AddField(
            model_name='couponapplication',
            name='per_user_limit',
            field=models.PositiveIntegerField(default=1, verbose_name='每人限领'),
        ),
        migrations.AddField(
            model_name='couponapplication',
            name='review_comment',
            field=models.TextField(blank=True, default='', verbose_name='审批意见'),
        ),
        migrations.AddField(
            model_name='leaderchangeapplication',
            name='change_type',
            field=models.CharField(choices=[('promotion', '晋升'), ('transfer', '平调'), ('replacement', '替换'), ('departure', '离职交接')], default='replacement', max_length=20, verbose_name='变更类型'),
        ),
        migrations.AddField(
            model_name='leaderchangeapplication',
            name='effective_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='生效日期'),
        ),
        migrations.AddField(
            model_name='leaderchangeapplication',
            name='handover_plan',
            field=models.TextField(blank=True, default='', verbose_name='交接计划'),
        ),
        migrations.AddField(
            model_name='leaderchangeapplication',
            name='review_comment',
            field=models.TextField(blank=True, default='', verbose_name='审批意见'),
        ),
    ]
