# Generated by Django 5.1 on 2026-06-23 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0011_add_application_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandrenameapplication',
            name='brand_description',
            field=models.TextField(blank=True, default='', verbose_name='品牌描述（提交时快照）'),
        ),
        migrations.AddField(
            model_name='brandrenameapplication',
            name='brand_is_active',
            field=models.BooleanField(default=True, verbose_name='品牌启用状态（提交时快照）'),
        ),
        migrations.AddField(
            model_name='brandrenameapplication',
            name='brand_logo_url',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='品牌Logo URL（提交时快照）'),
        ),
        migrations.AddField(
            model_name='brandrenameapplication',
            name='old_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='原名称（提交时快照）'),
        ),
        migrations.AddField(
            model_name='categoryrenameapplication',
            name='category_description',
            field=models.TextField(blank=True, default='', verbose_name='分类描述（提交时快照）'),
        ),
        migrations.AddField(
            model_name='categoryrenameapplication',
            name='category_level',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='分类层级（提交时快照）'),
        ),
        migrations.AddField(
            model_name='categoryrenameapplication',
            name='category_path',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='完整分类路径（提交时快照）'),
        ),
        migrations.AddField(
            model_name='categoryrenameapplication',
            name='impact_child_category_count',
            field=models.PositiveIntegerField(default=0, verbose_name='影响子分类数量'),
        ),
        migrations.AddField(
            model_name='categoryrenameapplication',
            name='old_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='原名称（提交时快照）'),
        ),
        migrations.AddField(
            model_name='categoryrenameapplication',
            name='parent_category_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='上级分类ID（提交时快照）'),
        ),
        migrations.AddField(
            model_name='categoryrenameapplication',
            name='parent_category_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='上级分类名称（提交时快照）'),
        ),
        migrations.AddField(
            model_name='couponapplication',
            name='applicable_category_names',
            field=models.TextField(blank=True, default='', verbose_name='适用分类名称（提交时快照，逗号分隔）'),
        ),
        migrations.AddField(
            model_name='couponapplication',
            name='applicable_product_names',
            field=models.TextField(blank=True, default='', verbose_name='适用商品名称（提交时快照，逗号分隔）'),
        ),
        migrations.AddField(
            model_name='couponapplication',
            name='campaign_purpose',
            field=models.TextField(blank=True, default='', verbose_name='活动目的'),
        ),
        migrations.AddField(
            model_name='couponapplication',
            name='expected_usage_count',
            field=models.PositiveIntegerField(default=0, verbose_name='预估使用人次'),
        ),
        migrations.AddField(
            model_name='couponapplication',
            name='target_audience',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='目标用户群'),
        ),
        migrations.AddField(
            model_name='leaderchangeapplication',
            name='group_category_count',
            field=models.PositiveIntegerField(default=0, verbose_name='分管分类数（提交时快照）'),
        ),
        migrations.AddField(
            model_name='leaderchangeapplication',
            name='group_description',
            field=models.TextField(blank=True, default='', verbose_name='分组描述（提交时快照）'),
        ),
        migrations.AddField(
            model_name='leaderchangeapplication',
            name='group_member_count',
            field=models.PositiveIntegerField(default=0, verbose_name='分组成员数（提交时快照）'),
        ),
        migrations.AddField(
            model_name='leaderchangeapplication',
            name='group_name_snapshot',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='分组名称（提交时快照）'),
        ),
        migrations.AddField(
            model_name='leaderchangeapplication',
            name='old_leader_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='原组长ID（提交时快照）'),
        ),
        migrations.AddField(
            model_name='leaderchangeapplication',
            name='old_leader_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='原组长用户名（提交时快照）'),
        ),
    ]
