# Generated by Django 5.1 on 2026-06-23 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0012_enhance_application_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='spu',
            name='specs',
            field=models.JSONField(blank=True, default=list, verbose_name='规格定义'),
        ),
    ]
