# Generated by Django 5.1 on 2026-07-28 09:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0016_missing_columns"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminnotification",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="过期时间"),
        ),
        migrations.AlterField(
            model_name="productmedia",
            name="alt_text",
            field=models.CharField(
                blank=True,
                default="",
                help_text="图片无障碍描述文本，用于 SEO 和屏幕阅读器",
                max_length=200,
                verbose_name="Alt 替代文本",
            ),
        ),
        migrations.AlterField(
            model_name="sku",
            name="alert_threshold",
            field=models.PositiveIntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="库存预警阈值",
            ),
        ),
        migrations.AlterField(
            model_name="sku",
            name="barcode",
            field=models.CharField(
                blank=True,
                default="",
                max_length=128,
                verbose_name="条形码 (UPC/EAN/ISBN)",
            ),
        ),
        migrations.AlterField(
            model_name="sku",
            name="cost_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="成本价",
            ),
        ),
        migrations.AlterField(
            model_name="sku",
            name="sku_code",
            field=models.CharField(
                blank=True, default="", max_length=64, verbose_name="SKU编码"
            ),
        ),
        migrations.AlterField(
            model_name="sku",
            name="version",
            field=models.PositiveIntegerField(default=0, verbose_name="乐观锁版本号"),
        ),
        migrations.AlterField(
            model_name="sku",
            name="weight",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=8, verbose_name="重量 (克)"
            ),
        ),
        migrations.AlterField(
            model_name="spu",
            name="product_kind",
            field=models.CharField(
                choices=[("physical", "实体商品"), ("virtual", "虚拟商品")],
                default="physical",
                help_text="physical=实体商品（需图片/物流）/ virtual=虚拟商品（隐藏图片区）",
                max_length=10,
                verbose_name="商品类型",
            ),
        ),
        migrations.AlterField(
            model_name="spu",
            name="requires_shipping",
            field=models.BooleanField(default=True, verbose_name="需要物流"),
        ),
        migrations.AlterField(
            model_name="spu",
            name="tags",
            field=models.JSONField(blank=True, default=list, verbose_name="标签列表"),
        ),
        migrations.AlterField(
            model_name="spu",
            name="taxable",
            field=models.BooleanField(default=True, verbose_name="需计税"),
        ),
        migrations.AlterField(
            model_name="tag",
            name="color",
            field=models.CharField(
                default="#e74c3c",
                help_text="HEX 色值，如 #e74c3c",
                max_length=7,
                verbose_name="标签颜色",
            ),
        ),
    ]
