# Generated by Django 5.2.16 on 2026-07-28 10:14

import json

from django.db import migrations
from django.utils import timezone


def _ids(value):
    if not value:
        return []
    try:
        parsed = json.loads(value)
    except (TypeError, ValueError):
        return []
    return parsed if isinstance(parsed, list) else []


def copy_coupon_applications(apps, schema_editor):
    Legacy = apps.get_model("goods", "CouponApplication")
    Application = apps.get_model("promotion", "CouponApplication")
    History = apps.get_model("promotion", "CouponApprovalHistory")
    Coupon = apps.get_model("promotion", "Coupon")
    now = timezone.now()

    for old in Legacy.objects.all().iterator(chunk_size=200):
        coupon = None
        if old.status == "approved" and old.coupon_code:
            coupon = Coupon.objects.filter(code=old.coupon_code).first()
        start_time = old.start_time or now
        end_time = old.end_time or (start_time + timezone.timedelta(days=365))
        status = {
            "approved": "active" if start_time <= now else "scheduled",
            "rejected": "rejected",
        }.get(old.status, "pending")
        application = Application.objects.create(
            id=old.id,
            coupon_name=old.coupon_name,
            coupon_code=old.coupon_code,
            discount_type=old.discount_type,
            amount=old.amount,
            min_amount=old.min_amount,
            max_discount=old.max_discount,
            stackable=old.stackable,
            total_count=old.total_count,
            per_user_limit=old.per_user_limit,
            start_time=start_time,
            end_time=end_time,
            applicable_categories=_ids(old.applicable_categories),
            applicable_products=_ids(old.applicable_products),
            applicable_category_names=old.applicable_category_names,
            applicable_product_names=old.applicable_product_names,
            expected_cost=old.expected_cost,
            expected_usage_count=old.expected_usage_count,
            target_audience=old.target_audience or "all",
            campaign_purpose=old.campaign_purpose,
            reason=old.reason,
            status=status,
            applicant_id=old.applicant_id,
            reviewer_id=old.reviewer_id,
            coupon_id=coupon.id if coupon else None,
            review_comment=old.review_comment,
            submitted_at=old.created_at,
            reviewed_at=old.reviewed_at,
        )
        Application.objects.filter(pk=application.pk).update(
            created_at=old.created_at,
            updated_at=old.reviewed_at or old.created_at,
        )
        history = History.objects.create(
            application_id=application.id,
            actor_id=old.reviewer_id or old.applicant_id,
            from_status="pending" if old.status != "pending" else "",
            to_status=status,
            comment=old.review_comment,
            snapshot={"legacy_id": old.id, "legacy_status": old.status},
        )
        History.objects.filter(pk=history.pk).update(
            created_at=old.reviewed_at or old.created_at,
        )


def restore_coupon_applications(apps, schema_editor):
    Legacy = apps.get_model("goods", "CouponApplication")
    Application = apps.get_model("promotion", "CouponApplication")
    for current in Application.objects.all().iterator(chunk_size=200):
        legacy_status = {
            "rejected": "rejected",
            "draft": "pending",
            "pending": "pending",
        }.get(current.status, "approved")
        restored = Legacy.objects.create(
            id=current.id,
            coupon_name=current.coupon_name,
            coupon_code=current.coupon_code,
            discount_type=current.discount_type,
            amount=current.amount,
            min_amount=current.min_amount,
            max_discount=current.max_discount,
            stackable=current.stackable,
            total_count=current.total_count,
            per_user_limit=current.per_user_limit,
            start_time=current.start_time,
            end_time=current.end_time,
            applicable_categories=json.dumps(current.applicable_categories or []),
            applicable_products=json.dumps(current.applicable_products or []),
            applicable_category_names=current.applicable_category_names,
            applicable_product_names=current.applicable_product_names,
            expected_cost=current.expected_cost,
            expected_usage_count=current.expected_usage_count,
            target_audience=current.target_audience,
            campaign_purpose=current.campaign_purpose,
            reason=current.reason,
            status=legacy_status,
            applicant_id=current.applicant_id,
            reviewer_id=current.reviewer_id,
            review_comment=current.review_comment,
            reviewed_at=current.reviewed_at,
        )
        Legacy.objects.filter(pk=restored.pk).update(created_at=current.created_at)


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0017_adminnotification_expires_at_and_more"),
        ("promotion", "0007_coupon_target_audience_couponapplication_and_more"),
    ]

    operations = [
        migrations.RunPython(copy_coupon_applications, restore_coupon_applications),
        migrations.DeleteModel(name="CouponApplication",),
    ]
