# Generated by Django 5.2.17 on 2026-08-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0020_spu_submitted_by_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='tag_type',
            field=models.CharField(choices=[('product', '产品标签'), ('activity', '活动标签')], default='product', help_text='产品标签：附着于商品描述（如 #上新）；活动标签：关联营销活动（如 #双十一）', max_length=20, verbose_name='标签类型'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(default='#e74c3c', help_text='HEX 色值，如 #e74c3c；仅作展示用途，标签本身是文本话题', max_length=7, verbose_name='标签颜色'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['tag_type'], name='idx_tag_type'),
        ),
    ]
