# Generated by Django 5.1 on 2026-07-26 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('superadmin', '超级管理员'), ('ops', '运维'), ('admin_leader', '管理组组长'), ('admin_member', '管理组组员'), ('customer', '普通用户')], max_length=32, verbose_name='角色')),
                ('perm_code', models.CharField(max_length=64, verbose_name='权限点')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='授予时间')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rbac_granted_perms', to=settings.AUTH_USER_MODEL, verbose_name='授予人')),
            ],
            options={
                'verbose_name': '角色权限',
                'verbose_name_plural': '角色权限',
                'db_table': 'rbac_role_permission',
                'ordering': ['role', 'perm_code'],
                'indexes': [models.Index(fields=['role'], name='idx_rbac_rp_role')],
                'unique_together': {('role', 'perm_code')},
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('superadmin', '超级管理员'), ('ops', '运维'), ('admin_leader', '管理组组长'), ('admin_member', '管理组组员'), ('customer', '普通用户')], max_length=32, verbose_name='角色')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='授予时间')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rbac_granted_roles', to=settings.AUTH_USER_MODEL, verbose_name='授予人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rbac_roles', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户角色',
                'verbose_name_plural': '用户角色',
                'db_table': 'rbac_user_role',
                'ordering': ['user_id', 'role'],
                'indexes': [models.Index(fields=['user'], name='idx_rbac_ur_user'), models.Index(fields=['role'], name='idx_rbac_ur_role')],
                'unique_together': {('user', 'role')},
            },
        ),
    ]
