# Generated by Django 5.1 on 2026-07-28 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0002_notification_expires_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OperationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("system", "系统"),
                            ("operation", "操作"),
                            ("notification", "通知"),
                            ("security", "安全"),
                            ("error", "错误"),
                        ],
                        max_length=20,
                        verbose_name="日志分类",
                    ),
                ),
                ("action", models.CharField(max_length=100, verbose_name="操作动作")),
                ("resource_type", models.CharField(max_length=50, verbose_name="资源类型")),
                (
                    "resource_id",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="资源 ID"
                    ),
                ),
                (
                    "detail",
                    models.JSONField(blank=True, default=dict, verbose_name="详情"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP 地址"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "操作日志",
                "verbose_name_plural": "操作日志",
                "db_table": "notification_operation_log",
                "ordering": ["-created_at"],
            },
        ),
    ]
