"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
from django.utils import timezone
from pathlib import Path
import os
import json

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

if os.getenv("DEL_ENV") != "prod":
    from dotenv import load_dotenv
    load_dotenv()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    from django.core.exceptions import ImproperlyConfigured
    raise ImproperlyConfigured(
        'DJANGO_SECRET_KEY environment variable is required. '
        'Generate one with: python -c "from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())"'
    )

# SECURITY WARNING: don't run with debug turned on in production!

# ALLOWED_HOSTS will be set in prod.py with a RuntimeError guard
# to prevent missing configuration in production.

DOMAIN = os.getenv('DOMAIN', 'http://127.0.0.1:8000')
APP_VERSION = os.getenv('APP_VERSION', 'dev')
GIT_COMMIT = os.getenv('GIT_COMMIT', 'unknown')
DJANGO_ENV = os.getenv('DJANGO_ENV', 'dev')
ENABLE_MOCK_PAYMENT = os.getenv(
    'ENABLE_MOCK_PAYMENT',
    'true' if DJANGO_ENV in ('dev', 'staging', 'local', 'test') else 'false',
).lower() == 'true'
MOCK_PAYMENT_SECRET = os.getenv('MOCK_PAYMENT_SECRET', SECRET_KEY)
TURNSTILE_SECRET_KEY = os.getenv('TURNSTILE_SECRET_KEY', '')
TURNSTILE_VERIFY_TIMEOUT = float(os.getenv('TURNSTILE_VERIFY_TIMEOUT', '3.0'))

# 平台与前端相关配置（欢迎邮件 / 验证链接使用）
PLATFORM_NAME = os.getenv('PLATFORM_NAME', 'Ziggner')
FRONTEND_URL = os.getenv('FRONTEND_URL', 'https://admin.ziggner.com')
SUPPORT_URL = os.getenv('SUPPORT_URL', 'https://ziggner.com/support')
# Application definition

INSTALLED_APPS = [
    'daphne',
    'django_prometheus',
    'corsheaders',  # 与 CorsMiddleware 配套，否则 CORS 配置可能不完整
    'utils',
    # rbac 是全站基础设施：业务 app 单向依赖它，故排在业务 app 之前
    'apps.rbac.apps.RbacConfig',
    'apps.users.apps.UsersConfig',
    'apps.goods.apps.GoodsConfig',
    'apps.cart.apps.CartConfig',
    'apps.order.apps.OrderConfig',
    'apps.address.apps.AddressConfig',
    'apps.payment.apps.PaymentConfig',
    'apps.review.apps.ReviewConfig',
    'apps.support.apps.SupportConfig',
    'apps.customer_service.apps.CustomerServiceConfig',
    'apps.notification.apps.NotificationConfig',
    'apps.promotion.apps.PromotionConfig',
    'apps.lovegoods.apps.LovegoodsConfig',
    'apps.tracking.apps.TrackingConfig',
    'apps.logistics.apps.LogisticsConfig',
    'apps.health',
    'channels',
    'drf_spectacular',
    'drf_spectacular_sidecar',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'rest_framework.authtoken',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_celery_beat',  # Celery Beat 数据库调度器
    'django_celery_results',  # Celery 结果存储
]

MIDDLEWARE = [
    'django_prometheus.middleware.PrometheusBeforeMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'utils.ip_whitelist_middleware.AdminIpWhitelistMiddleware',  # 管理后台 IP 白名单（ADMIN_IP_WHITELIST 配置，未配置则放行）
    'utils.cookie_domain_middleware.DynamicCookieDomainMiddleware',  # 按请求 Host 动态设定 Cookie Domain（localhost 去 Domain，否则 -.ziggner.com）
    'middleware.rate_limit.RateLimitMiddleware',
    'middleware.memory_watchdog.MemoryWatchdogMiddleware',  # 2C4G：RSS>85% 自保护（清 L1 缓存 + 回收空闲连接）
    'utils.exception_middleware.CustomExceptionMiddleware',
    'middleware.api_version.APIVersionMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'utils.csp_middleware.CSPMiddleware',  # API JSON 响应强制严格 CSP（纵深防御 MIME 嗅探/点击劫持），HTML 响应不受影响
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'middleware.jwt_blacklist.JWTBlacklistMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'utils.operation_log_middleware.OperationLogMiddleware',  # 操作日志：按用户类型/日期 层级存储
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_prometheus.middleware.PrometheusAfterMiddleware',
]

API_V1_SUNSET = os.getenv('API_V1_SUNSET', 'Wed, 30 Sep 2026 23:59:59 GMT')

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, '../templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'
ASGI_APPLICATION = 'project.asgi.application'

# ── Django Channels 配置 ──
# 关键：REST 由 gunicorn 处理、WebSocket 由 daphne 处理，二者是不同进程。
# 进程内 InMemoryChannelLayer 无法跨进程广播，导致「客服发消息 → 买家 WS 收不到实时推送」。
# 改用 Redis Channel Layer（复用已部署的 Redis，独立 DB /4 避免与缓存 /0、CELERY /2,/3 冲突）。
_CHANNEL_REDIS_BASE = os.getenv('REDIS_URL', 'redis://127.0.0.1:6379/0').rsplit('/', 1)[0]
CHANNEL_REDIS_URL = os.getenv('CHANNEL_REDIS_URL', _CHANNEL_REDIS_BASE + '/4')
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [CHANNEL_REDIS_URL],
            'capacity': 1500,
            'expiry': 3600,
        },
    },
}


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        # 2C4G：dj-db-conn-pool 提供 MySQL 连接池（MAX_CONNS 上限），防止连接泄漏/打满；
        # 配合 DJANGO_DB_DRIVER=pymysql（纯 Python 驱动）兼容 gevent 协程调度。
        'ENGINE': os.getenv('DB_ENGINE', 'dj_db_conn_pool.backends.mysql'),
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
        'CONN_MAX_AGE': 300,  # 5 分钟连接复用
        'CONN_HEALTH_CHECKS': True,  # 每次使用前检查连接健康
        'POOL_OPTIONS': {
            'MAX_CONNS': 15,  # 2C4G：单进程连接池上限 ≤15，防连接泄漏耗内存
            'RECYCLE_SEC': 300,  # 5 分钟回收空闲连接
        },
        'OPTIONS': {
            'charset': 'utf8mb4',
            'connect_timeout': 3,  # 连接超时 3s
            'read_timeout': 10,  # 查询超时 10s，防止慢查询阻塞
            'write_timeout': 10,  # 写入超时 10s
            # 生产保持 FK 检查开启；仅超时会话参数（测试环境可在 local.py 覆盖）
            'init_command': "SET SESSION wait_timeout=300, SESSION interactive_timeout=300",
        },
        'TEST': {
            'CHARSET': 'utf8mb4',
            'COLLATION': 'utf8mb4_unicode_ci',
            'SERIALIZE': False,  # 跳过数据序列化（部分 app 表缺失导致 serializing 崩溃）
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

# ============================================================
# 文件存储配置（Django 4.2+ STORAGES）
# 未来扩展：只需将 backend 改为 storages.backends.s3boto3.S3Boto3Storage
# 即可接入阿里云 OSS，无需修改任何业务代码
# ============================================================
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:8000",
    "http://localhost:8001",
    "http://127.0.0.1:8000",
    "http://127.0.0.1:8001",
]

# django-cors-headers 默认允许头 + 退款幂等键头（Idempotency-Key）
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'idempotency-key',
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'America/New_York'

SIMPLEUI_DEFAULT_THEME = 'admin.lte.css'

STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.getenv('STATIC_ROOT', os.path.join(BASE_DIR, 'static'))

# 静默 MySQL 不支持的约束警告
SILENCED_SYSTEM_CHECKS = ['models.W036']

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'utils.api_jwt_authentication.UsersJWTAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_THROTTLE_CLASSES': (
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ),
    # 限流速率可被环境变量 THROTTLE_RATES 覆写（JSON，测试/压测放开限流时设大值）。
    # 注意：不要设为 {} 空对象——AnonRateThrottle/UserRateThrottle 取不到 scope 速率
    # 会抛 ImproperlyConfigured("No default throttle rate set ...")，导致所有请求 500。
    'DEFAULT_THROTTLE_RATES': json.loads(os.getenv('THROTTLE_RATES', json.dumps({
        'anon': '100/hour',
        'user': '5000/hour',
        'admin_login': '5/minute',
        'admin_write': '60/minute',
        'admin_batch': '10/minute',
    }))),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    # 2C4G：默认 20 条/页，最大 100 条/页（上限防一次拉爆单 worker 内存）
    "DEFAULT_PAGINATION_CLASS": "utils.pagination.CappedPageNumberPagination",
    "PAGE_SIZE": 20,  # 每页 20 条数据
    "EXCEPTION_HANDLER": "utils.api_exception.custom_exception_handler",
}

# DRF Spectacular settings
SPECTACULAR_SETTINGS = {
    'TITLE': 'Ziggner 商城 API',
    'DESCRIPTION': (
        'Ziggner 精选综合商城接口文档。浏览器第一方会话使用 HttpOnly Cookie 与 CSRF；'
        'Apifox、移动端和服务端客户端使用 Bearer JWT；后台管理接口使用独立 Admin Token。'
    ),
    'VERSION': '1.0.0',
    'OAS_VERSION': '3.1.0',
    'DEFAULT_GENERATOR_CLASS': 'project.openapi.ZiggnerSchemaGenerator',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'DISABLE_ERRORS_AND_WARNINGS': False,
    'AUTHENTICATION_WHITELIST': [
        'utils.api_jwt_authentication.UsersJWTAuthentication',
        'apps.users.session_auth.CookieJWTAuthentication',
        'utils.admin_authentication.ExpiringTokenAuthentication',
    ],
    'POSTPROCESSING_HOOKS': ['project.openapi.postprocess_zh_cn_schema'],
    # 本地化 Swagger UI 资源，避免 CDN 被 CSP / Tracking Prevention 拦截
    'SWAGGER_UI_DIST': 'SIDECAR',
    'SWAGGER_UI_FAVICON_HREF': 'SIDECAR',
    'REDOC_DIST': 'SIDECAR',
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'persistAuthorization': True
    },
}

# ── 仅 MySQL：缓存/会话走 DB，去掉 Redis 进程 ──
# 验证码/限流/黑名单等共用 django_cache 表（启动时 createcachetable）
REDIS_MASTER_URL = os.getenv('REDIS_URL', 'redis://127.0.0.1:6379/0')
REDIS_SLAVE_URL = os.getenv('REDIS_SLAVE_URL', REDIS_MASTER_URL)


def _redis_cache(location, *, timeout=300):
    return {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': location,
        'TIMEOUT': timeout,
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'SOCKET_CONNECT_TIMEOUT': 2,
            'SOCKET_TIMEOUT': 2,
            # 缓存降级：Redis 宕机时缓存读异常被吞（get→None→DB 兜底），
            # 避免整站 500；锁走 raw redis 连接（utils.cache 互斥锁），异常照抛保持 fail-loud。
            'IGNORE_EXCEPTIONS': True,
            # 2C4G：每个 Redis 缓存别名连接池上限 ≤10，防止 Redis 连接数失控
            'CONNECTION_POOL_KWARGS': {'max_connections': 10},
        },
        'KEY_PREFIX': f"ziggner:{os.getenv('DJANGO_ENV', 'dev')}",
    }


CACHES = {
    'default': _redis_cache(REDIS_MASTER_URL),
    'rw_default': _redis_cache(REDIS_MASTER_URL),
    'rw_default_slave': _redis_cache(REDIS_SLAVE_URL),
    'session': _redis_cache(REDIS_MASTER_URL, timeout=86400),
    'verification_code': _redis_cache(REDIS_MASTER_URL, timeout=600),
    # 2C4G 二级缓存 L1：进程内 LocMem 近缓存（商品详情/分类树等读多写少数据），
    # 命中即省一次 Redis 网络往返；TTL 较短（见 utils/cache.py 两级读取）。
    'local': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'ziggner-local',
        'TIMEOUT': 600,
    },
}

SESSION_ENGINE = "django.contrib.sessions.backends.cached_db"
SESSION_CACHE_ALIAS = "session"

# ==================== 用户模块可扩展配置 ====================
# 后续调优只需改此处，无需改动业务代码
USERS_SETTINGS = {
    # 用户名
    'USERNAME_MIN_LENGTH': 3,
    'USERNAME_MAX_LENGTH': 15,
    # 密码 —— 须包含大小写字母和数字（OWASP 推荐 ≥ 8 位）
    'PASSWORD_MIN_LENGTH': 8,
    'PASSWORD_MAX_LENGTH': 25,
    'PASSWORD_REQUIRE_UPPER': True,
    'PASSWORD_REQUIRE_LOWER': True,
    'PASSWORD_REQUIRE_DIGIT': True,
    # 图片验证码
    'CAPTCHA_EXPIRE_SECONDS': 120,    # 2 分钟过期
    # 邮箱验证码（统一验证配置）
    'VERIFICATION_CODE_LENGTH': 6,
    'VERIFICATION_CODE_EXPIRE_SECONDS': 300,   # 5 分钟过期
    'VERIFICATION_RATE_LIMIT_SECONDS': 60,     # 60 秒发送间隔
    'VERIFICATION_MAX_ATTEMPTS': 5,     # 每条验证码最多尝试验证次数
    # 全局发送额度（防恶意刷爆发件账号日额度；163 免费邮箱日额度约 500 封，保守留余量）
    'VERIFICATION_GLOBAL_MINUTE_LIMIT': 10,   # 全系统每 60 秒最多发送验证码数
    'VERIFICATION_GLOBAL_DAILY_LIMIT': 200,   # 全系统每 24 小时最多发送验证码数
    # 邮箱验证令牌
    'EMAIL_VERIFICATION_TOKEN_EXPIRE_MINUTES': 15,  # 验证令牌有效期
    # 邮箱验证码（独立流程）
    'VERIFICATION_CODE_EXPIRE': 600,  # 10 分钟过期
    # 用户名修改冷却期
    'USERNAME_CHANGE_COOLDOWN_DAYS': 30,  # 修改用户名后需等待天数
}

# ==================== 邮件 SMTP 配置（163邮箱）====================
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.163.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '465'))
EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL', 'True').lower() == 'true'
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'False').lower() == 'true'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')  # 163邮箱授权码
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'Ziggner <noreply@163.com>')

# =============== 管理后台邮箱（163）===============
ADMIN_EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.163.com')
ADMIN_EMAIL_PORT = int(os.getenv('EMAIL_PORT', '465'))
ADMIN_EMAIL_USE_SSL = True
ADMIN_EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
ADMIN_EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
ADMIN_DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'Ziggner <deavenhui@163.com>')

# =============== 用户注册邮箱（独立配置，暂留空）===============
USER_EMAIL_HOST = os.getenv('USER_EMAIL_HOST', 'smtp.163.com')
USER_EMAIL_PORT = int(os.getenv('USER_EMAIL_PORT', '465'))
USER_EMAIL_USE_SSL = os.getenv('USER_EMAIL_USE_SSL', 'True').lower() == 'true'
USER_EMAIL_USE_TLS = os.getenv('USER_EMAIL_USE_TLS', 'False').lower() == 'true'
USER_EMAIL_HOST_USER = os.getenv('USER_EMAIL_HOST_USER', '')
USER_EMAIL_HOST_PASSWORD = os.getenv('USER_EMAIL_HOST_PASSWORD', '')
USER_DEFAULT_FROM_EMAIL = os.getenv('USER_DEFAULT_FROM_EMAIL', 'Ziggner <noreply@ziggner.com>')

# =============== 多发件账号池（额度感知轮换）===============
# 格式（JSON 数组字符串，.env 里配 EMAIL_ACCOUNTS）：
#   [{"host":"smtp.163.com","port":465,"user":"a@163.com","password":"授权码",
#     "from_email":"Ziggner <a@163.com>","use_ssl":true,"daily_limit":500},
#    {"host":"smtp.163.com","port":465,"user":"b@163.com","password":"授权码",
#     "from_email":"Ziggner <b@163.com>","use_ssl":true,"daily_limit":500}]
# 未配置时回退为单一账号（EMAIL_HOST_USER 等，兼容旧配置）。
import json as _json
_EMAIL_ACCOUNTS_RAW = os.getenv('EMAIL_ACCOUNTS', '')
if _EMAIL_ACCOUNTS_RAW:
    try:
        EMAIL_ACCOUNTS = _json.loads(_EMAIL_ACCOUNTS_RAW)
        for _acc in EMAIL_ACCOUNTS:
            _acc.setdefault('port', int(_acc.get('port', 465)))
            _acc.setdefault('use_ssl', True)
            _acc.setdefault('use_tls', False)
            _acc.setdefault('daily_limit', int(_acc.get('daily_limit', 500)))
    except Exception:
        EMAIL_ACCOUNTS = []
else:
    EMAIL_ACCOUNTS = []
if not EMAIL_ACCOUNTS:
    EMAIL_ACCOUNTS = [{
        'host': EMAIL_HOST,
        'port': EMAIL_PORT,
        'user': EMAIL_HOST_USER,
        'password': EMAIL_HOST_PASSWORD,
        'from_email': DEFAULT_FROM_EMAIL,
        'use_ssl': EMAIL_USE_SSL,
        'daily_limit': int(os.getenv('EMAIL_ACCOUNT_DAILY_LIMIT', '500')),
    }]

# Simple JWT settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timezone.timedelta(minutes=15),  # 访问令牌有效期15分钟 (F-003 修复)
    'REFRESH_TOKEN_LIFETIME': timezone.timedelta(hours=2),  # 刷新令牌 2 小时；配合 ROTATE_REFRESH_TOKENS 实现空闲超时（活跃刷新即续期，闲置>2h 自动登出）
    'ROTATE_REFRESH_TOKENS': True,  # 刷新令牌时自动更新刷新令牌
    'BLACKLIST_AFTER_ROTATION': True,  # 刷新后将旧的刷新令牌加入黑名单
    'UPDATE_LAST_LOGIN': True,  # 更新用户最后登录时间
    'ALGORITHM': 'HS256',  # 使用的加密算法
    'SIGNING_KEY': SECRET_KEY,  # 签名密钥，使用Django的SECRET_KEY
    'VERIFYING_KEY': None,  # 验证密钥，使用对称加密时为None
    'AUTH_HEADER_TYPES': ('Bearer',),  # 认证头类型
    'AUTH_HEADER_NAME': 'Authorization',  # 认证头名称
    'USER_ID_FIELD': 'id',  # 用户模型中用作用户ID的字段
    'USER_ID_CLAIM': 'user_id',  # token中用户ID的声明名称
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'JTI_CLAIM': 'jti',  # JWT ID声明，用于防止重放攻击
    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timezone.timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timezone.timedelta(days=1),
}

# 日志配置
LOG_LEVEL = os.getenv('LOG_LEVEL', 'DEBUG')
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "json",
        },
        "app_log": {
            "level": LOG_LEVEL,
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "logs/app.log",
            "maxBytes": 10_485_760,  # 10MB
            "backupCount": 5,
            "formatter": "verbose",
        },
        "celery_log": {
            "level": LOG_LEVEL,
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "logs/celery.log",
            "maxBytes": 10_485_760,
            "backupCount": 3,
            "formatter": "verbose",
        },
        "task_log": {
            "level": LOG_LEVEL,
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "logs/task.log",
            "maxBytes": 10_485_760,
            "backupCount": 3,
            "formatter": "verbose",
        },
        "task_error_log": {
            "level": "ERROR",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "logs/task_error.log",
            "maxBytes": 10_485_760,
            "backupCount": 3,
            "formatter": "verbose",
        },
    },
    "formatters": {
        "verbose": {
            "format": "[{levelname}]::{asctime}::{module}::{message}",
            "style": "{",
        },
        "simple": {
            "format": "[{levelname}] {message}",
            "style": "{",
        },
        "json": {
            "()": "utils.json_logging.JsonFormatter",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console", "app_log"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "django.request": {
            "handlers": ["console", "app_log"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "django.db.backends": {
            "handlers": ["console"],
            "level": "DEBUG" if os.getenv('LOG_SQL', 'false').lower() == 'true' else "INFO",
            "propagate": False,
        },
        "biz": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        # Celery 相关日志
        "celery": {
            "handlers": ["console", "celery_log"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "celery.task": {
            "handlers": ["console", "celery_log"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "celery.worker": {
            "handlers": ["console", "celery_log"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "celery.beat": {
            "handlers": ["console", "celery_log"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
    },
}

# ==================== 客服系统 ====================
# 说明：以下配置控制客服聊天系统的限流、文件上传、搜索等行为

# 客服消息限流：滑动时间窗口大小（秒），配合 CS_RATE_LIMIT_MAX 使用
CS_RATE_LIMIT_WINDOW = 60
# 客服消息限流：每个用户在滑动窗口内最多发送消息数
CS_RATE_LIMIT_MAX = 30
# 客服限流 Redis key 前缀，用于在 Redis 中区分不同限流场景
CS_RATE_LIMIT_KEY_PREFIX = 'cs:rate_limit:user'
# 客服图片上传：允许的 MIME 类型集合
CS_ALLOWED_IMAGE_TYPES = {'image/jpeg', 'image/png', 'image/gif'}
# 客服视频上传：允许的 MIME 类型集合
CS_ALLOWED_VIDEO_TYPES = {'video/mp4'}
# 客服图片上传：单张图片大小上限（字节），默认 10MB
CS_IMAGE_MAX_SIZE = 10 * 1024 * 1024
# 客服视频上传：单个视频大小上限（字节），默认 50MB
CS_VIDEO_MAX_SIZE = 50 * 1024 * 1024
# 客服图片上传：文件存储子目录
CS_IMAGE_UPLOAD_FOLDER = 'chat/images'
# 客服视频上传：文件存储子目录
CS_VIDEO_UPLOAD_FOLDER = 'chat/videos'
# 客服商品搜索：接口最多返回条数
CS_PRODUCT_SEARCH_LIMIT = 50
# 客服一对一：客服回复前用户最多连续发送消息数，超过后提示等待客服回复
CS_USER_MSG_LIMIT_BEFORE_REPLY = 5

# ==================== WebSocket ====================
# 说明：以下配置控制 WebSocket 连接的保活、重连和消息确认机制

# WebSocket 心跳：服务端发送 ping 的间隔（秒）
WS_PING_INTERVAL = 30
# WebSocket 心跳：等待客户端 pong 响应的超时时间（秒）
WS_PONG_TIMEOUT = 10
# WebSocket 心跳：从上次收到 pong 到断开连接的总超时（秒），建议等于 PING_INTERVAL + PONG_TIMEOUT
WS_PING_TOTAL_TIMEOUT = 40
# WebSocket 消息确认：ACK 最大重试次数，超过后标记为发送失败
WS_ACK_MAX_RETRIES = 3
# WebSocket 消息确认：ACK 重试间隔（秒）
WS_ACK_RETRY_DELAY = 5

# ==================== 商品系统（SPU）====================
# 说明：以下配置控制商品管理后台的列表分页、审核流程和媒体限制

# 商品列表：管理后台每页默认显示条数
SPU_ADMIN_DEFAULT_PAGE_SIZE = 20
# 商品审核：组长审核通过后自动上架的延迟时间（分钟），给运营预留操作窗口
SPU_SCHEDULED_PUBLISH_DELAY_MINUTES = 5
# 商品媒体：每个 SPU 最多允许的媒体文件数量（图片+视频合计）
SPU_MEDIA_MAX_COUNT = 6

# ==================== 用户系统 ====================
# 头像上传：允许的文件扩展名白名单
AVATAR_ALLOWED_EXTENSIONS = ('.jpg', '.jpeg', '.png', '.gif', '.webp')

# ==================== 限流（Rate Limit）====================
# 说明：按客户端 IP 进行请求频率限制，超过限制后封禁一段时间

# 限流统计窗口大小（秒）
RATE_LIMIT_WINDOW = 60
# 触发限流后的封禁时长（秒），封禁期间该 IP 所有请求返回 429
RATE_LIMIT_BLOCK_TTL = 300
# 各接口的限流阈值配置（单位：请求/秒/IP）
# 键为 API 路径（支持 fnmatch 通配），值为令牌桶容量= refill 速率（req/s）
# 通过 Redis+Lua 原子令牌桶实现（见 utils/token_bucket.py），触发即返回 429。
# 可通过环境变量 RATE_LIMITS 覆写（JSON 格式）。
# 统一 v1：无前缀旧版 /api/* 已废弃下线，仅保留 /api/v1/ 配置。
RATE_LIMITS = json.loads(os.getenv('RATE_LIMITS', json.dumps({
    '/api/v1/users/login/': 2.0,                # 登录：2 req/s/IP
    '/api/v1/users/session/login/': 2.0,
    '/api/v1/users/token/': 2.0,
    '/api/v1/users/register/': 1.0,             # 注册：1 req/s/IP
    '/api/v1/users/send-verify-code/': 0.2,     # 验证码：0.2 req/s/IP（约 5s/次）
    '/api/v1/order/checkout/': 5.0,             # 购买：5 req/s/IP
    '/api/v1/payment/create/': 5.0,             # 支付下单：5 req/s/IP
    '/api/v1/promotion/*/claim/': 2.0,
    '/api/v1/payment/webhook/*/': 60.0,         # 支付回调：高吞吐（白名单类）
})))

# 管理后台 API 限流：10 req/s per user（按登录用户计数，非 IP）
ADMIN_API_RATE_LIMIT = float(os.getenv('ADMIN_API_RATE_LIMIT', '10'))
ADMIN_API_RATE_LIMIT_PREFIX = '/api/v1/admin/'

# 单容器内存硬上限（MB），供内存看门狗计算 85% 阈值；与 docker-compose.prod.yml mem_limit 对齐
MEM_LIMIT_MB = int(os.getenv('MEM_LIMIT_MB', '544'))

# R2 上传异步化开关：开启后上传走 Celery（主线程返回 202 + 轮询地址），
# 关闭时保持原同步落盘（返回 200 + url）。默认关闭，待前端对接轮询后再翻 True。
ASYNC_UPLOAD_ENABLED = os.getenv('ASYNC_UPLOAD_ENABLED', 'false').lower() == 'true'

TRUSTED_PROXY_CIDRS = tuple(
    item.strip()
    for item in os.getenv(
        'TRUSTED_PROXY_CIDRS',
        '127.0.0.0/8,::1/128,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16',
    ).split(',')
    if item.strip()
)

# ==================== 操作日志 ====================
# 操作日志文件存储根路径（相对于项目根目录）
OPERATION_LOG_BASE_DIR = os.getenv(
    'OPERATION_LOG_BASE_DIR',
    str(BASE_DIR.parent / 'logs' / 'operations'),
)
# 触发审计日志记录的请求模式（方法:路径前缀），匹配任一即记录审计日志
AUDIT_ACTION_PATTERNS = {'POST:/api/payment/', 'POST:/api/order/', 'DELETE:'}

# ==================== 通知系统 ====================
# 通知列表：默认每页显示条数
NOTIFICATION_DEFAULT_PAGE_SIZE = 20
# 通知列表：Redis 缓存过期时间（秒），缓存用户通知列表以减少数据库查询
NOTIFICATION_LIST_CACHE_TTL = 120
# 未读计数：Redis 缓存过期时间（秒），缓存用户未读通知数
NOTIFICATION_UNREAD_CACHE_TTL = 60

# Celery 配置 —— 仅 MySQL（SQLAlchemy broker + django-db results），无 Redis/RabbitMQ
RABBITMQ_URL = os.getenv('RABBITMQ_URL', '')  # 废弃，保留兼容

def _celery_mysql_url():
    user = os.getenv('DB_USER', '')
    password = os.getenv('DB_PASSWORD', '')
    host = os.getenv('DB_HOST', '127.0.0.1')
    port = os.getenv('DB_PORT', '3306')
    name = os.getenv('DB_NAME', '')
    # SQLAlchemy MySQL URL（Celery broker）
    from urllib.parse import quote_plus
    return (
        f"sqla+mysql+pymysql://{quote_plus(user)}:{quote_plus(password)}"
        f"@{host}:{port}/{name}?charset=utf8mb4"
    )

CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://127.0.0.1:6379/2')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://127.0.0.1:6379/3')
CELERY_RESULT_EXTENDED = False
CELERY_RESULT_EXPIRES = int(os.getenv('CELERY_RESULT_EXPIRES', '3600'))  # 1h
CELERY_ACCEPT_CONTENT = ['json']  # 接受的内容类型
CELERY_TASK_SERIALIZER = 'json'  # 任务序列化方式
CELERY_RESULT_SERIALIZER = 'json'  # 结果序列化方式
CELERY_TIMEZONE = TIME_ZONE  # 时区
CELERY_TASK_TRACK_STARTED = True  # 跟踪任务开始
CELERY_TASK_TIME_LIMIT = int(os.getenv('CELERY_TASK_TIME_LIMIT', '300'))
CELERY_TASK_SOFT_TIME_LIMIT = int(os.getenv('CELERY_TASK_SOFT_TIME_LIMIT', '240'))
CELERY_LOG_LEVEL = LOG_LEVEL

# Broker 连接（SQLAlchemy / MySQL）
# 注意：SQLAlchemy transport 不接受 RabbitMQ 的 visibility_timeout 等参数
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_BROKER_TRANSPORT_OPTIONS = {
    'visibility_timeout': 3600,
    'socket_connect_timeout': 3,
    'socket_timeout': 5,
}

# 定义队列（按任务类型分离）
CELERY_TASK_QUEUES = {
    'default': {'exchange': 'default', 'routing_key': 'default'},
    'image_process': {'exchange': 'image_process', 'routing_key': 'image_process'},
    'batch_import': {'exchange': 'batch_import', 'routing_key': 'batch_import'},
    'ranking': {'exchange': 'ranking', 'routing_key': 'ranking'},
}

# Celery 任务路由
CELERY_TASK_ROUTES = {
    'apps.goods.tasks.process_product_image': {'queue': 'image_process'},
    'apps.goods.tasks.upload_media_to_cloud': {'queue': 'image_process'},
    'apps.goods.tasks.clean_expired_media': {'queue': 'default'},
    'apps.goods.tasks.batch_import_products': {'queue': 'batch_import'},
    'apps.goods.tasks.recalc_sales_ranking': {'queue': 'ranking'},
    'apps.goods.tasks.warm_hot_product_cache': {'queue': 'ranking'},
    'apps.goods.tasks.warm_category_cache': {'queue': 'default'},
    'apps.order.tasks.auto_cancel_unpaid_orders': {'queue': 'default'},
    'apps.order.tasks.auto_complete_orders': {'queue': 'default'},
}

# Celery 重试策略
CELERY_TASK_DEFAULT_QUEUE = os.getenv('CELERY_TASK_DEFAULT_QUEUE', 'default')
CELERY_TASK_CREATE_MISSING_QUEUES = True  # SQLAlchemy broker 自动建队列表
CELERY_TASK_ACKS_LATE = True  # 任务执行完成后才确认
CELERY_TASK_REJECT_ON_WORKER_LOST = True  # 工作进程丢失时拒绝任务
CELERY_TASK_DEFAULT_RETRY_DELAY = 60  # 默认重试延迟（1分钟）
CELERY_TASK_MAX_RETRIES = 3  # 最大重试次数
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'  # 使用数据库调度器
CELERY_BEAT_SCHEDULE = {
    'warm-hot-product-cache-every-30min': {
        'task': 'apps.goods.tasks.warm_hot_product_cache',
        'schedule': 1800.0,  # 30 分钟
        'options': {'queue': 'ranking'},
    },
    'warm-category-cache-every-12hours': {
        'task': 'apps.goods.tasks.warm_category_cache',
        'schedule': 43200.0,  # 12 小时
        'options': {'queue': 'default'},
    },
    'warm-bloom-filter-every-1hour': {
        'task': 'apps.goods.tasks.warm_bloom_filter_task',
        'schedule': 3600.0,  # 1 小时 — 重建布隆过滤器
        'options': {'queue': 'default'},
    },
    'auto-cancel-unpaid-orders-every-5min': {
        'task': 'apps.order.tasks.auto_cancel_unpaid_orders',
        'schedule': 300.0,  # 5 分钟
        'options': {'queue': 'default'},
    },
    'auto-complete-delivered-orders-every-6hours': {
        'task': 'apps.order.tasks.auto_complete_orders',
        'schedule': 21600.0,  # 6 小时
        'options': {'queue': 'default'},
    },
    'execute-scheduled-publish-every-1min': {
        'task': 'goods.execute_scheduled_publish',
        'schedule': 60.0,  # 1 分钟
        'options': {'queue': 'default'},
    },
    'clean-expired-media-every-1hour': {
        'task': 'goods.clean_expired_media',
        'schedule': 3600.0,  # 1 小时
        'options': {'queue': 'default'},
    },
    'sync-expired-payments-every-15min': {
        'task': 'payment.sync_expired_payments',
        'schedule': 900.0,  # 15 分钟 — 补偿丢失的支付回调
        'options': {'queue': 'default'},
    },
    'reconcile-unknown-refunds-every-5min': {
        'task': 'payment.reconcile_unknown_refunds',
        'schedule': 300.0,
        'options': {'queue': 'default'},
    },
}

REFUND_RECONCILIATION_BATCH_SIZE = int(os.getenv('REFUND_RECONCILIATION_BATCH_SIZE', '20'))

# ==================== Celery Worker 内存限制（2C4G：偏紧，防泄漏） ====================
# 单位 KiB（Celery --max-memory-per-child）。120MB 子进程 + concurrency=1 适配 256m 容器。
CELERY_WORKER_MAX_MEMORY_PER_CHILD = int(os.getenv('CELERY_WORKER_MAX_MEMORY_PER_CHILD', str(120 * 1024)))
CELERY_WORKER_MAX_TASKS_PER_CHILD = int(os.getenv('CELERY_WORKER_MAX_TASKS_PER_CHILD', '40'))

# ==================== 文件存储配置 ====================
# 切换后端: 'local' | 'cos' | 'oss' | 'r2'
FILE_STORAGE = os.getenv('FILE_STORAGE', 'local')
FILE_STORAGE_MAX_SIZE = int(os.getenv('FILE_STORAGE_MAX_SIZE', '10'))
FILE_STORAGE_ALLOWED_TYPES = [
    'image/jpeg', 'image/png', 'image/webp', 'image/gif',
    'video/mp4', 'video/webm',
]

# 腾讯云 COS
COS_SECRET_ID = os.getenv('COS_SECRET_ID', '')
COS_SECRET_KEY = os.getenv('COS_SECRET_KEY', '')
COS_REGION = os.getenv('COS_REGION', 'ap-guangzhou')
COS_BUCKET = os.getenv('COS_BUCKET', '')

# 阿里云 OSS
OSS_ACCESS_KEY_ID = os.getenv('OSS_ACCESS_KEY_ID', '')
OSS_ACCESS_KEY_SECRET = os.getenv('OSS_ACCESS_KEY_SECRET', '')
OSS_ENDPOINT = os.getenv('OSS_ENDPOINT', '')
OSS_BUCKET = os.getenv('OSS_BUCKET', '')

# Cloudflare R2
R2_ACCOUNT_ID = os.getenv('R2_ACCOUNT_ID', '')
R2_ACCESS_KEY_ID = os.getenv('R2_ACCESS_KEY_ID', '')
R2_SECRET_ACCESS_KEY = os.getenv('R2_SECRET_ACCESS_KEY', '')
R2_BUCKET = os.getenv('R2_BUCKET', '')
R2_PUBLIC_URL = os.getenv('R2_PUBLIC_URL', '')

# 媒体数量限制
MEDIA_MAX_IMAGES_PER_SPU = int(os.getenv('MEDIA_MAX_IMAGES_PER_SPU', '5'))
MEDIA_MAX_VIDEOS_PER_SPU = int(os.getenv('MEDIA_MAX_VIDEOS_PER_SPU', '1'))
MEDIA_MAX_FILE_SIZE_MB = int(os.getenv('MEDIA_MAX_FILE_SIZE_MB', '10'))

# ==================== 商品缓存 TTL 配置 ====================
GOODS_CACHE_TTL = {
    'CATEGORY_TREE': 3600 * 6,        # 6 小时（几乎不变）
    'BRAND_LIST': 3600 * 12,          # 12 小时
    'SPU_DETAIL': 3600 * 1,           # 1 小时
    'SPU_LIST': 1800,                 # 30 分钟
    'SKU_DETAIL': 1800,               # 30 分钟
    'HOT_PRODUCTS': 300,              # 5 分钟（定时刷新）
    'SPECS_ALL': 3600 * 3,            # 3 小时
    'ATTRIBUTES_BY_CATEGORY': 3600 * 3,  # 3 小时
    'MEDIA_LIST': 1800,               # 30 分钟（媒体列表）
    'SPU_KIND': 3600,                 # 1 小时（商品类型）
}

# ==================== 支付网关配置 ====================
# PayPal
PAYPAL_CLIENT_ID = os.getenv('PAYPAL_CLIENT_ID', '')
PAYPAL_CLIENT_SECRET = os.getenv('PAYPAL_CLIENT_SECRET', '')
PAYPAL_WEBHOOK_ID = os.getenv('PAYPAL_WEBHOOK_ID', '')
PAYPAL_BASE_URL = os.getenv('PAYPAL_BASE_URL', 'https://api-m.paypal.com')

# Stripe（信用卡）
STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY', '')
STRIPE_WEBHOOK_SECRET = os.getenv('STRIPE_WEBHOOK_SECRET', '')

# 支付默认币种
DEFAULT_CURRENCY = os.getenv('DEFAULT_CURRENCY', 'USD')

# ==================== 订单缓存 TTL 配置 ====================
ORDER_CACHE_TTL = {
    'ORDER_DETAIL': 300,             # 5 分钟
    'ORDER_LIST': 120,               # 2 分钟
}

# ==================== 订单自动任务配置 ====================
ORDER_AUTO_SETTINGS = {
    'CANCEL_UNPAID_MINUTES': 15,     # 未支付订单 15 分钟后自动取消
    'COMPLETE_DELIVERED_DAYS': 7,    # 已签收 7 天后自动完成
}

# ==================== 搜索配置 ====================
SEARCH_SETTINGS = {
    'DEFAULT_PAGE_SIZE': 20,
    'MAX_PAGE_SIZE': 100,
    'SUGGEST_MIN_CHARS': 2,
}

ENVIRONMENT = os.getenv("DJANGO_ENV", "prod")  # 默认开发环境

# ==================== 第三方登录（Social OAuth）配置 ====================
# OAuth 2.0 Client credentials — 在环境变量中设置
SOCIAL_AUTH_GOOGLE_CLIENT_ID = os.getenv('SOCIAL_AUTH_GOOGLE_CLIENT_ID', '')
SOCIAL_AUTH_GOOGLE_SECRET = os.getenv('SOCIAL_AUTH_GOOGLE_SECRET', '')

SOCIAL_AUTH_FACEBOOK_APP_ID = os.getenv('SOCIAL_AUTH_FACEBOOK_APP_ID', '')
SOCIAL_AUTH_FACEBOOK_SECRET = os.getenv('SOCIAL_AUTH_FACEBOOK_SECRET', '')

SOCIAL_AUTH_LINKEDIN_CLIENT_ID = os.getenv('SOCIAL_AUTH_LINKEDIN_CLIENT_ID', '')
SOCIAL_AUTH_LINKEDIN_SECRET = os.getenv('SOCIAL_AUTH_LINKEDIN_SECRET', '')

# OAuth 回调地址前缀（前端地址）
SOCIAL_AUTH_REDIRECT_BASE = os.getenv('SOCIAL_AUTH_REDIRECT_BASE', 'http://localhost:12700')
