"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
from django.utils import timezone
from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

if os.getenv("DEL_ENV") != "prod":
    from dotenv import load_dotenv
    load_dotenv()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    from django.core.exceptions import ImproperlyConfigured
    raise ImproperlyConfigured(
        'DJANGO_SECRET_KEY environment variable is required. '
        'Generate one with: python -c "from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())"'
    )

# SECURITY WARNING: don't run with debug turned on in production!

# ALLOWED_HOSTS will be set in prod.py with a RuntimeError guard
# to prevent missing configuration in production.

DOMAIN = os.getenv('DOMAIN', 'http://127.0.0.1:8000')
# Application definition

INSTALLED_APPS = [
    'daphne',
    'django_prometheus',
    'utils',
    'apps.users.apps.UsersConfig',
    'apps.goods.apps.GoodsConfig',
    'apps.cart.apps.CartConfig',
    'apps.order.apps.OrderConfig',
    'apps.address.apps.AddressConfig',
    'apps.payment.apps.PaymentConfig',
    'apps.review.apps.ReviewConfig',
    'apps.support.apps.SupportConfig',
    'apps.customer_service.apps.CustomerServiceConfig',
    'apps.notification.apps.NotificationConfig',
    'apps.promotion.apps.PromotionConfig',
    'apps.lovegoods.apps.LovegoodsConfig',
    'apps.tracking.apps.TrackingConfig',
    'apps.logistics.apps.LogisticsConfig',
    'apps.terms.apps.TermsConfig',
    'apps.health',
    'channels',
    'drf_spectacular',
    'drf_spectacular_sidecar',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'rest_framework.authtoken',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_celery_beat',  # Celery Beat 数据库调度器
    'django_celery_results',  # Celery 结果存储
]

MIDDLEWARE = [
    'django_prometheus.middleware.PrometheusBeforeMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'middleware.rate_limit.RateLimitMiddleware',
    'utils.exception_middleware.CustomExceptionMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'middleware.jwt_blacklist.JWTBlacklistMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'utils.operation_log_middleware.OperationLogMiddleware',  # 操作日志：按用户类型/日期 层级存储
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_prometheus.middleware.PrometheusAfterMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, '../templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'
ASGI_APPLICATION = 'project.asgi.application'

# ── Django Channels 配置 ──
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [f'{os.getenv("REDIS_URL", "redis://redis:6379")}/4'],
            'symmetric_encryption_keys': [SECRET_KEY],
            'capacity': 1500,
            'expiry': 60,
        },
    },
}


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.getenv('DB_ENGINE', 'django_prometheus.db.backends.mysql'),
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
        'CONN_MAX_AGE': 300,  # 5 分钟连接复用
        'CONN_HEALTH_CHECKS': True,  # 每次使用前检查连接健康
        'POOL_OPTIONS': {
            'MAX_CONNS': 12,  # 限制最大连接数，防止连接泄漏耗内存
            'RECYCLE_SEC': 300,  # 5 分钟回收空闲连接
        },
        'OPTIONS': {
            'charset': 'utf8mb4',
            'connect_timeout': 3,  # 连接超时 3s
            'read_timeout': 10,  # 查询超时 10s，防止慢查询阻塞
            'write_timeout': 10,  # 写入超时 10s
            'init_command': "SET SESSION foreign_key_checks=0, SESSION wait_timeout=300, SESSION interactive_timeout=300",  # 先禁用 FK 检查（兼容测试建表），再设超时
        },
        'TEST': {
            'CHARSET': 'utf8mb4',
            'COLLATION': 'utf8mb4_unicode_ci',
            'SERIALIZE': False,  # 跳过数据序列化（部分 app 表缺失导致 serializing 崩溃）
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

# ============================================================
# 文件存储配置（Django 4.2+ STORAGES）
# 未来扩展：只需将 backend 改为 storages.backends.s3boto3.S3Boto3Storage
# 即可接入阿里云 OSS，无需修改任何业务代码
# ============================================================
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:8000",
    "http://localhost:8001",
    "http://127.0.0.1:8000",
    "http://127.0.0.1:8001",
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'America/New_York'

SIMPLEUI_DEFAULT_THEME = 'admin.lte.css'

STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.getenv('STATIC_ROOT', os.path.join(BASE_DIR, 'static'))

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'utils.api_jwt_authentication.UsersJWTAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_THROTTLE_CLASSES': (
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ),
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',
        'user': '1000/hour',
        'admin_login': '5/minute',
        'admin_write': '60/minute',
        'admin_batch': '10/minute',
    },
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",  # 分页
    "PAGE_SIZE": 10,  # 每页 10 条数据
    "EXCEPTION_HANDLER": "utils.api_exception.custom_exception_handler",
}

# DRF Spectacular settings
SPECTACULAR_SETTINGS = {
    'TITLE': 'Backend API',
    'DESCRIPTION': '后端 API',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'DISABLE_ERRORS_AND_WARNINGS': True,   # 165 unique W001 warnings are deliberate: /api/* & /api/v1/* share same views → expected opId collisions; schema correct with _2 suffixes
    'AUTHENTICATION_WHITELIST': ['utils.api_jwt_authentication.UsersJWTAuthentication'],
    # 本地化 Swagger UI 资源，避免 CDN 被 CSP / Tracking Prevention 拦截
    'SWAGGER_UI_DIST': 'SIDECAR',
    'SWAGGER_UI_FAVICON_HREF': 'SIDECAR',
    'REDOC_DIST': 'SIDECAR',
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'persistAuthorization': True
    },
    'SECURITY': [{'Bearer': []}],
    'SECURITY_SCHEMES': {
        'Bearer': {
        'type': 'http',
        'scheme': 'bearer',
        'bearerFormat': 'JWT',  # 指定 JWT 格式
        }
    }
}

# ── Redis 读写分离 (Master-Slave) ──
# Master: 写操作 (SET/DEL/INCR/KEYS/LOCK)
# Slave:  读操作 (GET/MGET)
# 本地开发时两者指向同一实例；生产环境通过环境变量分离
REDIS_MASTER_URL = os.getenv('REDIS_URL', 'redis://redis:6379')
REDIS_SLAVE_URL = os.getenv('REDIS_SLAVE_URL', os.getenv('REDIS_URL', 'redis://redis:6379'))

# Cache —— 5 个 Redis 逻辑库
# DB 0: 通用缓存 (rw_default=master, rw_default_slave=slave)
# DB 1: Session
# DB 2: 验证码缓存 (邮箱 + 短信)
# DB 3: Celery broker / results
CACHES = {
    # ── 读写分离 default 缓存 ──
    "rw_default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"{REDIS_MASTER_URL}/0",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "SOCKET_CONNECT_TIMEOUT": 5,
            "SOCKET_TIMEOUT": 5,
            "RETRY_ON_TIMEOUT": True,
            "MAX_CONNECTIONS": 32,  # 限制连接池大小，防止内存耗尽
            "CONNECTION_POOL_KWARGS": {
                "max_connections": 32,  # 实际连接池上限
                "retry_on_timeout": True,
                "health_check_interval": 30,  # 30s 健康检查，清理死连接
            },
            "COMPRESSOR": "django_redis.compressors.zlib.ZlibCompressor",
            "SERIALIZER": "django_redis.serializers.json.JSONSerializer",
        }
    },
    "rw_default_slave": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"{REDIS_SLAVE_URL}/0",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "SOCKET_CONNECT_TIMEOUT": 5,
            "SOCKET_TIMEOUT": 5,
            "RETRY_ON_TIMEOUT": True,
            "MAX_CONNECTIONS": 32,
            "CONNECTION_POOL_KWARGS": {
                "max_connections": 32,
                "retry_on_timeout": True,
                "health_check_interval": 30,
            },
            "COMPRESSOR": "django_redis.compressors.zlib.ZlibCompressor",
            "SERIALIZER": "django_redis.serializers.json.JSONSerializer",
        }
    },
    # ── 兼容旧代码的 default 别名 → 指向 master ──
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"{REDIS_MASTER_URL}/0",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "SOCKET_CONNECT_TIMEOUT": 5,
            "SOCKET_TIMEOUT": 5,
            "RETRY_ON_TIMEOUT": True,
            "MAX_CONNECTIONS": 32,
            "CONNECTION_POOL_KWARGS": {
                "max_connections": 32,
                "retry_on_timeout": True,
                "health_check_interval": 30,
            },
            "COMPRESSOR": "django_redis.compressors.zlib.ZlibCompressor",
            "SERIALIZER": "django_redis.serializers.json.JSONSerializer",
        }
    },
    "session": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"{REDIS_MASTER_URL}/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "SOCKET_CONNECT_TIMEOUT": 5,
            "SOCKET_TIMEOUT": 5,
            "RETRY_ON_TIMEOUT": True,
            "MAX_CONNECTIONS": 16,
            "CONNECTION_POOL_KWARGS": {
                "max_connections": 16,
                "retry_on_timeout": True,
                "health_check_interval": 30,
            },
            "COMPRESSOR": "django_redis.compressors.zlib.ZlibCompressor",
            "SERIALIZER": "django_redis.serializers.json.JSONSerializer",
        }
    },
    "verification_code": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"{REDIS_MASTER_URL}/2",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "SOCKET_CONNECT_TIMEOUT": 5,
            "SOCKET_TIMEOUT": 5,
            "RETRY_ON_TIMEOUT": True,
            "MAX_CONNECTIONS": 16,
            "CONNECTION_POOL_KWARGS": {
                "max_connections": 16,
                "retry_on_timeout": True,
                "health_check_interval": 30,
            },
        }
    },
}

# Session —— 使用独立的 Redis DB 1
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "session"

# ==================== 用户模块可扩展配置 ====================
# 后续调优只需改此处，无需改动业务代码
USERS_SETTINGS = {
    # 用户名
    'USERNAME_MIN_LENGTH': 3,
    'USERNAME_MAX_LENGTH': 15,
    # 密码 —— 须包含大小写字母和数字（OWASP 推荐 ≥ 8 位）
    'PASSWORD_MIN_LENGTH': 8,
    'PASSWORD_MAX_LENGTH': 25,
    'PASSWORD_REQUIRE_UPPER': True,
    'PASSWORD_REQUIRE_LOWER': True,
    'PASSWORD_REQUIRE_DIGIT': True,
    # 图片验证码
    'CAPTCHA_EXPIRE_SECONDS': 120,    # 2 分钟过期
    # 短信验证码
    'SMS_CODE_LENGTH': 6,
    'SMS_CODE_EXPIRE_SECONDS': 300,   # 5 分钟过期
    'SMS_RATE_LIMIT_SECONDS': 60,     # 60 秒发送间隔
    'SMS_MAX_VERIFY_ATTEMPTS': 5,     # 每条验证码最多尝试验证次数
    # 邮箱验证令牌
    'EMAIL_VERIFICATION_TOKEN_EXPIRE_MINUTES': 15,  # 验证令牌有效期
    # 邮箱验证码（独立流程）
    'VERIFICATION_CODE_EXPIRE': 600,  # 10 分钟过期
    # 用户名修改冷却期
    'USERNAME_CHANGE_COOLDOWN_DAYS': 30,  # 修改用户名后需等待天数
}

# ==================== 邮件 SMTP 配置（163邮箱）====================
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.163.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '465'))
EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL', 'True').lower() == 'true'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')  # 163邮箱授权码
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'Ziggner <noreply@163.com>')

# =============== 管理后台邮箱（163）===============
ADMIN_EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.163.com')
ADMIN_EMAIL_PORT = int(os.getenv('EMAIL_PORT', '465'))
ADMIN_EMAIL_USE_SSL = True
ADMIN_EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
ADMIN_EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
ADMIN_DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'Ziggner <deavenhui@163.com>')

# =============== 用户注册邮箱（独立配置，暂留空）===============
USER_EMAIL_HOST = os.getenv('USER_EMAIL_HOST', 'smtp.163.com')
USER_EMAIL_PORT = int(os.getenv('USER_EMAIL_PORT', '465'))
USER_EMAIL_USE_SSL = True
USER_EMAIL_HOST_USER = os.getenv('USER_EMAIL_HOST_USER', '')
USER_EMAIL_HOST_PASSWORD = os.getenv('USER_EMAIL_HOST_PASSWORD', '')
USER_DEFAULT_FROM_EMAIL = os.getenv('USER_DEFAULT_FROM_EMAIL', 'Ziggner <noreply@ziggner.com>')

# Simple JWT settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timezone.timedelta(minutes=15),  # 访问令牌有效期15分钟 (F-003 修复)
    'REFRESH_TOKEN_LIFETIME': timezone.timedelta(days=7),  # 刷新令牌有效期7天
    'ROTATE_REFRESH_TOKENS': True,  # 刷新令牌时自动更新刷新令牌
    'BLACKLIST_AFTER_ROTATION': True,  # 刷新后将旧的刷新令牌加入黑名单
    'UPDATE_LAST_LOGIN': True,  # 更新用户最后登录时间
    'ALGORITHM': 'HS256',  # 使用的加密算法
    'SIGNING_KEY': SECRET_KEY,  # 签名密钥，使用Django的SECRET_KEY
    'VERIFYING_KEY': None,  # 验证密钥，使用对称加密时为None
    'AUTH_HEADER_TYPES': ('Bearer',),  # 认证头类型
    'AUTH_HEADER_NAME': 'Authorization',  # 认证头名称
    'USER_ID_FIELD': 'id',  # 用户模型中用作用户ID的字段
    'USER_ID_CLAIM': 'user_id',  # token中用户ID的声明名称
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'JTI_CLAIM': 'jti',  # JWT ID声明，用于防止重放攻击
    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timezone.timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timezone.timedelta(days=1),
}

# 日志配置
LOG_LEVEL = os.getenv('LOG_LEVEL', 'DEBUG')
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
        "app_log": {
            "level": LOG_LEVEL,
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "logs/app.log",
            "maxBytes": 10_485_760,  # 10MB
            "backupCount": 5,
            "formatter": "verbose",
        },
        "celery_log": {
            "level": LOG_LEVEL,
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "logs/celery.log",
            "maxBytes": 10_485_760,
            "backupCount": 3,
            "formatter": "verbose",
        },
        "task_log": {
            "level": LOG_LEVEL,
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "logs/task.log",
            "maxBytes": 10_485_760,
            "backupCount": 3,
            "formatter": "verbose",
        },
        "task_error_log": {
            "level": "ERROR",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "logs/task_error.log",
            "maxBytes": 10_485_760,
            "backupCount": 3,
            "formatter": "verbose",
        },
    },
    "formatters": {
        "verbose": {
            "format": "[{levelname}]::{asctime}::{module}::{message}",
            "style": "{",
        },
        "simple": {
            "format": "[{levelname}] {message}",
            "style": "{",
        },
        "json": {
            "format": '{"timestamp": "%(asctime)s", "level": "%(levelname)s", '
                      '"logger": "%(name)s", "module": "%(module)s", '
                      '"message": "%(message)s"}',
            "style": "%",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console", "app_log"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "django.request": {
            "handlers": ["console", "app_log"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "django.db.backends": {
            "handlers": ["console"],
            "level": "DEBUG" if os.getenv('LOG_SQL', 'false').lower() == 'true' else "INFO",
            "propagate": False,
        },
        "biz": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        # Celery 相关日志
        "celery": {
            "handlers": ["console", "celery_log"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "celery.task": {
            "handlers": ["console", "celery_log"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "celery.worker": {
            "handlers": ["console", "celery_log"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "celery.beat": {
            "handlers": ["console", "celery_log"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
    },
}

# ==================== 客服系统 ====================
# 说明：以下配置控制客服聊天系统的限流、文件上传、搜索等行为

# 客服消息限流：滑动时间窗口大小（秒），配合 CS_RATE_LIMIT_MAX 使用
CS_RATE_LIMIT_WINDOW = 60
# 客服消息限流：每个用户在滑动窗口内最多发送消息数
CS_RATE_LIMIT_MAX = 30
# 客服限流 Redis key 前缀，用于在 Redis 中区分不同限流场景
CS_RATE_LIMIT_KEY_PREFIX = 'cs:rate_limit:user'
# 客服图片上传：允许的 MIME 类型集合
CS_ALLOWED_IMAGE_TYPES = {'image/jpeg', 'image/png', 'image/gif'}
# 客服视频上传：允许的 MIME 类型集合
CS_ALLOWED_VIDEO_TYPES = {'video/mp4'}
# 客服图片上传：单张图片大小上限（字节），默认 10MB
CS_IMAGE_MAX_SIZE = 10 * 1024 * 1024
# 客服视频上传：单个视频大小上限（字节），默认 50MB
CS_VIDEO_MAX_SIZE = 50 * 1024 * 1024
# 客服图片上传：文件存储子目录
CS_IMAGE_UPLOAD_FOLDER = 'chat/images'
# 客服视频上传：文件存储子目录
CS_VIDEO_UPLOAD_FOLDER = 'chat/videos'
# 客服商品搜索：接口最多返回条数
CS_PRODUCT_SEARCH_LIMIT = 50
# 客服一对一：客服回复前用户最多连续发送消息数，超过后提示等待客服回复
CS_USER_MSG_LIMIT_BEFORE_REPLY = 5

# ==================== WebSocket ====================
# 说明：以下配置控制 WebSocket 连接的保活、重连和消息确认机制

# WebSocket 心跳：服务端发送 ping 的间隔（秒）
WS_PING_INTERVAL = 30
# WebSocket 心跳：等待客户端 pong 响应的超时时间（秒）
WS_PONG_TIMEOUT = 10
# WebSocket 心跳：从上次收到 pong 到断开连接的总超时（秒），建议等于 PING_INTERVAL + PONG_TIMEOUT
WS_PING_TOTAL_TIMEOUT = 40
# WebSocket 消息确认：ACK 最大重试次数，超过后标记为发送失败
WS_ACK_MAX_RETRIES = 3
# WebSocket 消息确认：ACK 重试间隔（秒）
WS_ACK_RETRY_DELAY = 5

# ==================== 商品系统（SPU）====================
# 说明：以下配置控制商品管理后台的列表分页、审核流程和媒体限制

# 商品列表：管理后台每页默认显示条数
SPU_ADMIN_DEFAULT_PAGE_SIZE = 20
# 商品审核：组长审核通过后自动上架的延迟时间（分钟），给运营预留操作窗口
SPU_SCHEDULED_PUBLISH_DELAY_MINUTES = 5
# 商品媒体：每个 SPU 最多允许的媒体文件数量（图片+视频合计）
SPU_MEDIA_MAX_COUNT = 6

# ==================== 用户系统 ====================
# 头像上传：允许的文件扩展名白名单
AVATAR_ALLOWED_EXTENSIONS = ('.jpg', '.jpeg', '.png', '.gif', '.webp')

# ==================== 限流（Rate Limit）====================
# 说明：按客户端 IP 进行请求频率限制，超过限制后封禁一段时间

# 限流统计窗口大小（秒）
RATE_LIMIT_WINDOW = 60
# 触发限流后的封禁时长（秒），封禁期间该 IP 所有请求返回 429
RATE_LIMIT_BLOCK_TTL = 300
# 各接口的限流阈值配置（次/窗口）
# 键为 API 路径，值为每窗口内允许的最大请求次数
RATE_LIMITS = {
    '/api/users/login/': 60,                 # 登录：60次/分钟/IP
    '/api/users/register/': 30,              # 注册：30次/分钟/IP
    '/api/users/send-verify-code/': 5,       # 发送验证码：5次/分钟/IP
    '/api/order/checkout/': 30,              # 下单：30次/分钟/IP
}

# ==================== 操作日志 ====================
# 操作日志文件存储根路径（相对于项目根目录）
OPERATION_LOG_BASE_DIR = 'logs/operations'
# 触发审计日志记录的请求模式（方法:路径前缀），匹配任一即记录审计日志
AUDIT_ACTION_PATTERNS = {'POST:/api/payment/', 'POST:/api/order/', 'DELETE:'}

# ==================== 通知系统 ====================
# 通知列表：默认每页显示条数
NOTIFICATION_DEFAULT_PAGE_SIZE = 20
# 通知列表：Redis 缓存过期时间（秒），缓存用户通知列表以减少数据库查询
NOTIFICATION_LIST_CACHE_TTL = 120
# 未读计数：Redis 缓存过期时间（秒），缓存用户未读通知数
NOTIFICATION_UNREAD_CACHE_TTL = 60

# Celery 配置
# 消息代理 —— 使用 RabbitMQ（更可靠的消息确认机制）
RABBITMQ_URL = os.getenv('RABBITMQ_URL', 'amqp://admin:admin@rabbitmq:5672//')
CELERY_BROKER_URL = RABBITMQ_URL
CELERY_RESULT_BACKEND = f"{REDIS_MASTER_URL}/3"  # 结果后端保留 Redis
CELERY_ACCEPT_CONTENT = ['json']  # 接受的内容类型
CELERY_TASK_SERIALIZER = 'json'  # 任务序列化方式
CELERY_RESULT_SERIALIZER = 'json'  # 结果序列化方式
CELERY_TIMEZONE = TIME_ZONE  # 时区
CELERY_TASK_TRACK_STARTED = True  # 跟踪任务开始
CELERY_TASK_TIME_LIMIT = 30 * 60  # 任务超时时间（30分钟）
CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60  # 软超时时间（25分钟）
CELERY_LOG_LEVEL = LOG_LEVEL

# RabbitMQ 连接配置
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_BROKER_TRANSPORT_OPTIONS = {
    'visibility_timeout': 3600,
    'confirm_publish': True,
}

# 定义队列（按任务类型分离）
CELERY_TASK_QUEUES = {
    'default': {'exchange': 'default', 'routing_key': 'default'},
    'image_process': {'exchange': 'image_process', 'routing_key': 'image_process'},
    'batch_import': {'exchange': 'batch_import', 'routing_key': 'batch_import'},
    'ranking': {'exchange': 'ranking', 'routing_key': 'ranking'},
}

# Celery 任务路由
CELERY_TASK_ROUTES = {
    'apps.goods.tasks.process_product_image': {'queue': 'image_process'},
    'apps.goods.tasks.upload_media_to_cloud': {'queue': 'image_process'},
    'apps.goods.tasks.clean_expired_media': {'queue': 'default'},
    'apps.goods.tasks.batch_import_products': {'queue': 'batch_import'},
    'apps.goods.tasks.recalc_sales_ranking': {'queue': 'ranking'},
    'apps.goods.tasks.warm_hot_product_cache': {'queue': 'ranking'},
    'apps.goods.tasks.warm_category_cache': {'queue': 'default'},
    'apps.order.tasks.auto_cancel_unpaid_orders': {'queue': 'default'},
    'apps.order.tasks.auto_complete_orders': {'queue': 'default'},
}

# Celery 重试策略
CELERY_TASK_ACKS_LATE = True  # 任务执行完成后才确认
CELERY_TASK_REJECT_ON_WORKER_LOST = True  # 工作进程丢失时拒绝任务
CELERY_TASK_DEFAULT_RETRY_DELAY = 60  # 默认重试延迟（1分钟）
CELERY_TASK_MAX_RETRIES = 3  # 最大重试次数
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'  # 使用数据库调度器
CELERY_BEAT_SCHEDULE = {
    'warm-hot-product-cache-every-30min': {
        'task': 'apps.goods.tasks.warm_hot_product_cache',
        'schedule': 1800.0,  # 30 分钟
        'options': {'queue': 'ranking'},
    },
    'warm-category-cache-every-12hours': {
        'task': 'apps.goods.tasks.warm_category_cache',
        'schedule': 43200.0,  # 12 小时
        'options': {'queue': 'default'},
    },
    'warm-bloom-filter-every-1hour': {
        'task': 'apps.goods.tasks.warm_bloom_filter_task',
        'schedule': 3600.0,  # 1 小时 — 重建布隆过滤器
        'options': {'queue': 'default'},
    },
    'auto-cancel-unpaid-orders-every-5min': {
        'task': 'apps.order.tasks.auto_cancel_unpaid_orders',
        'schedule': 300.0,  # 5 分钟
        'options': {'queue': 'default'},
    },
    'auto-complete-delivered-orders-every-6hours': {
        'task': 'apps.order.tasks.auto_complete_orders',
        'schedule': 21600.0,  # 6 小时
        'options': {'queue': 'default'},
    },
    'execute-scheduled-publish-every-1min': {
        'task': 'goods.execute_scheduled_publish',
        'schedule': 60.0,  # 1 分钟
        'options': {'queue': 'default'},
    },
    'clean-expired-media-every-1hour': {
        'task': 'goods.clean_expired_media',
        'schedule': 3600.0,  # 1 小时
        'options': {'queue': 'default'},
    },
    'sync-expired-payments-every-15min': {
        'task': 'payment.sync_expired_payments',
        'schedule': 900.0,  # 15 分钟 — 补偿丢失的支付回调
        'options': {'queue': 'default'},
    },
}

# ==================== Celery Worker 内存限制 ====================
CELERY_WORKER_MAX_MEMORY_PER_CHILD = 200 * 1024  # 200MB 子进程内存上限，超限自动重启
CELERY_WORKER_MAX_TASKS_PER_CHILD = 50           # 50 个任务后重启子进程，防泄漏

# ==================== 文件存储配置 ====================
# 切换后端: 'local' | 'cos' | 'oss' | 'r2'
FILE_STORAGE = os.getenv('FILE_STORAGE', 'local')
FILE_STORAGE_MAX_SIZE = int(os.getenv('FILE_STORAGE_MAX_SIZE', '10'))
FILE_STORAGE_ALLOWED_TYPES = [
    'image/jpeg', 'image/png', 'image/webp', 'image/gif',
    'video/mp4', 'video/webm',
]

# 腾讯云 COS
COS_SECRET_ID = os.getenv('COS_SECRET_ID', '')
COS_SECRET_KEY = os.getenv('COS_SECRET_KEY', '')
COS_REGION = os.getenv('COS_REGION', 'ap-guangzhou')
COS_BUCKET = os.getenv('COS_BUCKET', '')

# 阿里云 OSS
OSS_ACCESS_KEY_ID = os.getenv('OSS_ACCESS_KEY_ID', '')
OSS_ACCESS_KEY_SECRET = os.getenv('OSS_ACCESS_KEY_SECRET', '')
OSS_ENDPOINT = os.getenv('OSS_ENDPOINT', '')
OSS_BUCKET = os.getenv('OSS_BUCKET', '')

# Cloudflare R2
R2_ACCOUNT_ID = os.getenv('R2_ACCOUNT_ID', '')
R2_ACCESS_KEY_ID = os.getenv('R2_ACCESS_KEY_ID', '')
R2_SECRET_ACCESS_KEY = os.getenv('R2_SECRET_ACCESS_KEY', '')
R2_BUCKET = os.getenv('R2_BUCKET', '')
R2_PUBLIC_URL = os.getenv('R2_PUBLIC_URL', '')

# 媒体数量限制
MEDIA_MAX_IMAGES_PER_SPU = int(os.getenv('MEDIA_MAX_IMAGES_PER_SPU', '5'))
MEDIA_MAX_VIDEOS_PER_SPU = int(os.getenv('MEDIA_MAX_VIDEOS_PER_SPU', '1'))
MEDIA_MAX_FILE_SIZE_MB = int(os.getenv('MEDIA_MAX_FILE_SIZE_MB', '10'))

# ==================== 商品缓存 TTL 配置 ====================
GOODS_CACHE_TTL = {
    'CATEGORY_TREE': 3600 * 6,        # 6 小时（几乎不变）
    'BRAND_LIST': 3600 * 12,          # 12 小时
    'SPU_DETAIL': 3600 * 1,           # 1 小时
    'SPU_LIST': 1800,                 # 30 分钟
    'SKU_DETAIL': 1800,               # 30 分钟
    'HOT_PRODUCTS': 300,              # 5 分钟（定时刷新）
    'SPECS_ALL': 3600 * 3,            # 3 小时
    'ATTRIBUTES_BY_CATEGORY': 3600 * 3,  # 3 小时
    'MEDIA_LIST': 1800,               # 30 分钟（媒体列表）
    'SPU_KIND': 3600,                 # 1 小时（商品类型）
}

# ==================== 支付网关配置 ====================
# PayPal
PAYPAL_CLIENT_ID = os.getenv('PAYPAL_CLIENT_ID', '')
PAYPAL_CLIENT_SECRET = os.getenv('PAYPAL_CLIENT_SECRET', '')
PAYPAL_WEBHOOK_ID = os.getenv('PAYPAL_WEBHOOK_ID', '')
PAYPAL_BASE_URL = os.getenv('PAYPAL_BASE_URL', 'https://api-m.paypal.com')

# Stripe（信用卡）
STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY', '')
STRIPE_WEBHOOK_SECRET = os.getenv('STRIPE_WEBHOOK_SECRET', '')

# 支付默认币种
DEFAULT_CURRENCY = os.getenv('DEFAULT_CURRENCY', 'USD')

# ==================== 订单缓存 TTL 配置 ====================
ORDER_CACHE_TTL = {
    'ORDER_DETAIL': 300,             # 5 分钟
    'ORDER_LIST': 120,               # 2 分钟
}

# ==================== 订单自动任务配置 ====================
ORDER_AUTO_SETTINGS = {
    'CANCEL_UNPAID_MINUTES': 5,      # 未支付订单 5 分钟后自动取消
    'COMPLETE_DELIVERED_DAYS': 7,    # 已签收 7 天后自动完成
}

# ==================== 搜索配置 ====================
SEARCH_SETTINGS = {
    'DEFAULT_PAGE_SIZE': 20,
    'MAX_PAGE_SIZE': 100,
    'SUGGEST_MIN_CHARS': 2,
}

ENVIRONMENT = os.getenv("DJANGO_ENV", "prod")  # 默认开发环境

# ==================== 第三方登录（Social OAuth）配置 ====================
# OAuth 2.0 Client credentials — 在环境变量中设置
SOCIAL_AUTH_GOOGLE_CLIENT_ID = os.getenv('SOCIAL_AUTH_GOOGLE_CLIENT_ID', '')
SOCIAL_AUTH_GOOGLE_SECRET = os.getenv('SOCIAL_AUTH_GOOGLE_SECRET', '')

SOCIAL_AUTH_FACEBOOK_APP_ID = os.getenv('SOCIAL_AUTH_FACEBOOK_APP_ID', '')
SOCIAL_AUTH_FACEBOOK_SECRET = os.getenv('SOCIAL_AUTH_FACEBOOK_SECRET', '')

SOCIAL_AUTH_LINKEDIN_CLIENT_ID = os.getenv('SOCIAL_AUTH_LINKEDIN_CLIENT_ID', '')
SOCIAL_AUTH_LINKEDIN_SECRET = os.getenv('SOCIAL_AUTH_LINKEDIN_SECRET', '')

# OAuth 回调地址前缀（前端地址）
SOCIAL_AUTH_REDIRECT_BASE = os.getenv('SOCIAL_AUTH_REDIRECT_BASE', 'http://localhost:5173')
