# Ziggner — Cloudflare Workers + Static Assets
name = "ziggner"
compatibility_date = "2026-08-01"

[assets]
directory = "./dist/"

[[routes]]
pattern = "www.ziggner.com"
custom_domain = true

[[routes]]
pattern = "admin.ziggner.com"
custom_domain = true

[[routes]]
pattern = "shop.ziggner.com"
custom_domain = true
