# Generated by Django 5.2.15 on 2026-06-18 03:32

import apps.order.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(default=apps.order.models.generate_order_no, max_length=20, unique=True, verbose_name='订单号')),
                ('status', models.CharField(choices=[('pending_payment', 'Pending Payment'), ('paid', 'Paid'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending_payment', max_length=20, verbose_name='订单状态')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='商品总价')),
                ('actual_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='实付金额')),
                ('shipping_name', models.CharField(max_length=50, verbose_name='收货人')),
                ('shipping_phone', models.CharField(max_length=20, verbose_name='收货电话')),
                ('shipping_address', models.JSONField(default=dict, verbose_name='收货地址')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='结算币种')),
                ('payment_method', models.CharField(blank=True, choices=[('alipay', 'Alipay'), ('wechat', 'WeChat Pay'), ('card', 'Bank Card')], default='', max_length=20, verbose_name='支付方式')),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('refunding', 'Refunding'), ('refunded', 'Refunded')], default='unpaid', max_length=20, verbose_name='支付状态')),
                ('payment_no', models.CharField(blank=True, default='', max_length=64, verbose_name='支付流水号')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='付款时间')),
                ('tracking_no', models.CharField(blank=True, default='', max_length=50, verbose_name='快递单号')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='发货时间')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='签收时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='取消时间')),
                ('cancel_reason', models.CharField(blank=True, default='', max_length=500, verbose_name='取消原因')),
                ('buyer_remark', models.CharField(blank=True, default='', max_length=500, verbose_name='买家备注')),
                ('seller_remark', models.CharField(blank=True, default='', max_length=500, verbose_name='卖家备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'db_table': 'order_order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AfterSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('after_sale_no', models.CharField(default=apps.order.models.generate_after_sale_no, max_length=20, unique=True, verbose_name='售后单号')),
                ('type', models.CharField(choices=[('return', '退货退款'), ('exchange', '换货'), ('reship', '补发')], max_length=20, verbose_name='售后类型')),
                ('reason', models.TextField(verbose_name='申请原因')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='退款金额')),
                ('status', models.CharField(choices=[('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('processing', 'Processing'), ('completed', 'Completed')], default='pending_review', max_length=20, verbose_name='售后状态')),
                ('evidence', models.JSONField(default=list, verbose_name='凭证图片')),
                ('admin_remark', models.CharField(blank=True, default='', max_length=500, verbose_name='审核意见')),
                ('refunded_at', models.DateTimeField(blank=True, null=True, verbose_name='退款完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='after_sales', to='order.order', verbose_name='订单')),
            ],
            options={
                'verbose_name': '售后单',
                'verbose_name_plural': '售后单',
                'db_table': 'order_after_sale',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spu_name', models.CharField(max_length=200, verbose_name='商品名称')),
                ('sku_code', models.CharField(max_length=100, verbose_name='SKU 编码')),
                ('spec_snapshot', models.JSONField(default=list, verbose_name='规格快照')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='下单时单价')),
                ('quantity', models.PositiveIntegerField(verbose_name='数量')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='小计')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order', verbose_name='订单')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='goods.sku', verbose_name='SKU')),
            ],
            options={
                'verbose_name': '订单项',
                'verbose_name_plural': '订单项',
                'db_table': 'order_order_item',
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'status'], name='order_order_user_id_f784ac_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_no'], name='order_order_order_n_6f3729_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='order_order_status_2f1723_idx'),
        ),
        migrations.AddIndex(
            model_name='aftersale',
            index=models.Index(fields=['order'], name='order_after_order_i_9df2e6_idx'),
        ),
        migrations.AddIndex(
            model_name='aftersale',
            index=models.Index(fields=['status'], name='order_after_status_d04a75_idx'),
        ),
    ]
