# Generated by Django 5.1 on 2026-06-19 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_add_cart_indexes'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order'], name='idx_orderitem_order'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['sku'], name='idx_orderitem_sku'),
        ),
    ]
