# Generated by Django 5.1 on 2026-07-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_add_orderitem_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="version",
            field=models.PositiveIntegerField(default=0, verbose_name="乐观锁版本号"),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("alipay", "Alipay"),
                    ("wechat", "WeChat Pay"),
                    ("card", "Bank Card"),
                    ("paypal", "PayPal"),
                    ("stripe", "Credit/Debit Card (Stripe)"),
                ],
                default="",
                max_length=20,
                verbose_name="支付方式",
            ),
        ),
    ]
