# Generated by Django 5.2.17 on 2026-09-02 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_order_checkout_idempotency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('paypal', 'PayPal'), ('stripe', 'Credit/Debit Card (Stripe)')], default='', max_length=20, verbose_name='支付方式'),
        ),
    ]
