# Generated by Django 5.2.17 on 2026-10-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('paypal', 'PayPal'), ('stripe', 'Credit/Debit Card (Stripe)'), ('creem', 'Creem')], default='', max_length=20, verbose_name='支付方式'),
        ),
    ]