# Generated by Django 5.2.15 on 2026-06-18 03:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='收货人')),
                ('phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('country', models.CharField(default='China', max_length=100, verbose_name='国家')),
                ('region', models.CharField(max_length=100, verbose_name='州/省')),
                ('city', models.CharField(max_length=100, verbose_name='城市')),
                ('address_line', models.CharField(max_length=300, verbose_name='详细地址')),
                ('postal_code', models.CharField(blank=True, default='', max_length=20, verbose_name='邮编')),
                ('is_default', models.BooleanField(default=False, verbose_name='默认地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '收货地址',
                'verbose_name_plural': '收货地址',
                'db_table': 'address_address',
                'ordering': ['-is_default', '-created_at'],
                'indexes': [models.Index(fields=['user', 'is_default'], name='address_add_user_id_34bb22_idx')],
            },
        ),
    ]
