# Generated by Django 5.1 on 2026-07-06 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("goods", "0014_sku_version"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="主题"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "进行中"), ("closed", "已关闭")],
                        default="open",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                (
                    "cart_snapshot",
                    models.JSONField(blank=True, default=list, verbose_name="购物车快照"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "admin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_conversations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="处理客服",
                    ),
                ),
                (
                    "spu",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="support_conversations",
                        to="goods.spu",
                        verbose_name="关联商品",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="support_conversations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "客服对话",
                "verbose_name_plural": "客服对话",
                "db_table": "support_conversation",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sender",
                    models.CharField(
                        choices=[("user", "用户"), ("admin", "客服")],
                        max_length=8,
                        verbose_name="发送者",
                    ),
                ),
                (
                    "content",
                    models.TextField(blank=True, default="", verbose_name="文字内容"),
                ),
                (
                    "attachments",
                    models.JSONField(blank=True, default=list, verbose_name="附件"),
                ),
                (
                    "product_snapshot",
                    models.JSONField(blank=True, null=True, verbose_name="商品快照"),
                ),
                ("is_system", models.BooleanField(default=False, verbose_name="系统消息")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="发送时间"),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="support.conversation",
                        verbose_name="对话",
                    ),
                ),
            ],
            options={
                "verbose_name": "客服消息",
                "verbose_name_plural": "客服消息",
                "db_table": "support_message",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["user", "status"], name="support_con_user_id_bed716_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(fields=["status"], name="support_con_status_13c6dd_idx"),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["conversation", "created_at"],
                name="support_mes_convers_da2d9b_idx",
            ),
        ),
    ]
